### ISSUE TITLE
Satellite view per default

### ISSUE THREAD

**Issue by philgib** [hpneo/gmaps#106]
Anyway please to add themap type: 'SATTELLITE'  default option on the  map ?

**Comment by szTheory** [comment]
Hola Gustavo. Thanks for writing this great library! One request: can you add `mapType: 'satellite'` to the documentation somewhere? I had to come here to figure out how to do that since mapType is not listed on the official documentation. Thanks!

**Comment by hpneo** [comment]
Sure, I need to update the documentation someday soon...
