### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined  gmaps.js:1514

### ISSUE THREAD

**Issue by mutley** [hpneo/gmaps#126]
I am getting this error any ideas?

I am using the exact code in the basic example.

**Comment by tucq88** [comment]
To any one who get into this problem (`common.js:48 Uncaught TypeError: Cannot read property 'prototype' of undefined`) from Google .

Just include your API KEY with Google map script and you will be fine. Like `<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=APIKeyFromGoogle"></script>`. 

Struggled this problem for hours T_T Damn you Google.

**Comment by theel0ja** [comment]
@tucq88 I'm still getting the error.
Tested jQuery 2.2.4 and 1.9.1 -> not working
Using 0.4.24 version of gmaps.min.js
My code: https://gist.github.com/theel0ja/7fb237e2a5d129b7f6f41721189fcfe2

Error Message:
![Error Message]
(https://i.imgur.com/BaNZuHZ.png)

**Comment by fmkoba** [comment]
Getting the same error here, the funny thing is in my localhost dev it's working nicely, my problem is when I push it to production, the map loads for an instant, then I get the error message mentioned in the post above.

**Comment by tucq88** [comment]
@theel0ja I downloaded your html and only add my API key then [it works](https://gyazo.com/3a32a6266a7c73068650ffeb68f3a917). 

Is there any chance that your API key is not correct ? Try to create a new one.

@fmkoba Yeah i was same  as you. Localhost works great without API key, and after uploaded  to server, map blinks and error shows up. After added API key, problem gone. So funny hah ?

**Comment by fmkoba** [comment]
@tucq88  Tried it with the API key as well, no luck on that, the funny thing is, that I was using the github hosted pages as a quick staging server and there it works perfectly

**Comment by fmkoba** [comment]
@tucq88 I take that back, I think it was cached somewhere, working now, thanks for the help guys

**Comment by horusware** [comment]
Introduciendo la key de la api de google map ya funciona y se soluciona el error

**Comment by mogita** [comment]
For "prototype of undefined" like errors, please try to fetch an api key from google: https://developers.google.com/maps/documentation/javascript/

And this better be pointed out in the docs, as google seems to be enforcing the api key.

**Comment by lunfel** [comment]
For me it was that the key restrictions were not set up correctly.

I was using `*.mydomain.com/*` but this didn't work for the base domain, so I had to add `mydomain.com/*` also. Then it started to work again.

**Comment by LemonBaba** [comment]
I had still the same error after including the api key. Additionaly I had to include the version:

`<script src="https://maps.googleapis.com/maps/api/js?v=3&key=API_KEY"></script>`

**Comment by seanrockster** [comment]
I'm having he same issues described above. I'm on localhost currently. If i do not specify a key then i can see the map and add markers but i get the cannot read property blah blah etc message. If i specify a key, then i cannot see the map.

**Comment by seanrockster** [comment]
And 2 minutes later i see that i need to enable the Javascript api in the google console.

**Comment by bcastagna** [comment]
Javascript errors, still very intuitive...
More accurate solution:
- Go to Google Cloud Plateform (Google API console),
- "API & Services" on the left menu,
- "Library" on the left Menu,
- In "Google Maps APIs" section, choose "Google Maps JavaScript API",
- And, very intuitive again, click "Enable" at the top of this page [https://i.imgur.com/YcmMZ5G.png](url)

**Comment by alessandrostein** [comment]
We recently have the same error:

For solve we:

* Include the script with the token;
* Active in the dashboard, the Google Maps JavaScript API;
* Confirm your domain.
* Settings the restriction for access.

<img width="627" alt="captura de tela 2018-03-13 as 16 13 45" src="https://user-images.githubusercontent.com/4340946/37364627-c7c4c17c-26d9-11e8-9964-d7876eb75c01.png">

**Comment by filipemtro** [comment]
I solve removing type="text/javascript" from js api include.

**Comment by Cat5TV** [comment]
> Javascript errors, still very intuitive...
> More accurate solution:
> 
> * Go to Google Cloud Plateform (Google API console),
> * "API & Services" on the left menu,
> * "Library" on the left Menu,
> * In "Google Maps APIs" section, choose "Google Maps JavaScript API",
> * And, very intuitive again, click "Enable" at the top of this page https://i.imgur.com/YcmMZ5G.png

I hate to bump an old topic, but in 2019 this is still an issue, and you saved me a lot of frustration. I'd issued my API key just fine, but never thought to check if the js was "enabled" - there is, after all, no hint that it is disabled. Just a useless error that tells nothing. Thanks for the fix. Enable Google Maps JavaScript API. #facepalm.

**Comment by pavansai54** [comment]
TypeError: Cannot read property 'prototype' of undefined
i have this error ,please let me know we having the problem?

**Comment by hpneo** [comment]
@pavansai54 are you including the Google Maps JavaScript API script with the API key? See https://github.com/hpneo/gmaps/issues/126#issuecomment-235219798, https://github.com/hpneo/gmaps/issues/126#issuecomment-334491727 and https://github.com/hpneo/gmaps/issues/126#issuecomment-372786175
