### ISSUE TITLE
Make safe for concatenation

### ISSUE THREAD

**Issue by WickyNilliams** [hpneo/gmaps#216]
This library can cause issues with concatenation as it does not end (or start!) with a semicolon . The safest thing to do would be to wrap in a immediately executing function with a delimiting character at either end. e.g.

``` javascript
;(function(win) {
    //code here
    win.GMaps = GMaps;
}(window));
```

**Comment by hpneo** [comment]
If not fixed, it will be fixed in v1.0.0
