### ISSUE TITLE
JSHint configuration

### ISSUE THREAD

**Issue by WickyNilliams** [hpneo/gmaps#223]
So I've gone through all the JSHint options. The list below are those options that seem like they may be applicable. I've pre-checked those which directly translate from the coding standards in `CONTRIBUTING.md`.

I'd like to start a discussion as to which options fit best, then I'll go off, setup the grunt task and make the code meet those standards. 

Here we go, sorry if it seems daunting, there's not that many of them really :)
## Enforcing Options
- [ ] **bitwise**   - This option prohibits the use of bitwise operators such as ^ (XOR), | (OR) and others. Bitwise operators are very rare in JavaScript programs and quite often & is simply a mistyped &&.
- [x] **camelcase** - This option allows you to force all variable names to use either camelCase style or UPPER_CASE with underscores.
- [x] **curly**     - This option requires you to always put curly braces around blocks in loops and conditionals. JavaScript allows you to omit curly braces when the block consists of only one statement
- [x] **eqeqeq**    - This options prohibits the use of == and != in favor of === and !==.
- [ ] **es3**       - This option tells JSHint that your code needs to adhere to ECMAScript 3 specification. Use this option if you need your program to be executable in older browsers—such as Internet Explorer 6/7/8—and other legacy JavaScript environments.
- [ ] **forin**     - This option requires all for in loops to filter object's items. 
- [ ] **immed**     - This option prohibits the use of immediate function invocations without wrapping them in parentheses. Wrapping parentheses assists readers of your code in understanding that the expression is the result of a function, and not the function itself.
- [x] **indent**    - This option enforces specific tab width for your code
- [ ] **latedef**   - This option prohibits the use of a variable before it was defined. JavaScript has function scope only and, in addition to that, all variables are always moved—or hoisted— to the top of the function. This behavior can lead to some very nasty bugs and that's why it is safer to always use variable only after they have been explicitly defined.
- [x] **newcap**    - This option requires you to capitalize names of constructor functions. Capitalizing functions that are intended to be used with new operator is just a convention that helps programmers to visually distinguish constructor functions from other types of functions to help spot mistakes when using this.
- [ ] **noarg**     - This option prohibits the use of arguments.caller and arguments.callee. Both .caller and .callee make quite a few optimizations impossible so they were deprecated in future versions of JavaScript. In fact, ECMAScript 5 forbids the use of arguments.callee in strict mode.
- [ ] **noempty**   - This option warns when you have an empty block in your code. JSLint was originally warning for all empty blocks and we simply made it optional. There were no studies reporting that empty blocks in JavaScript break your code in any way.
- [ ] **nonew**     - This option prohibits the use of constructor functions for side-effects.
- [ ] **quotmark**  - This option enforces the consistency of quotation marks used throughout your code. It accepts three values: true if you don't want to enforce one particular style but want some consistency, "single" if you want to allow only single quotes and "double" if you want to allow only double quotes.
- [ ] **undef**     - This option prohibits the use of explicitly undeclared variables. This option is very useful for spotting leaking and mistyped variables.
- [ ] **unused**    - This option warns when you define and never use your variables. It is very useful for general code cleanup, especially when used in addition to undef.
- [x] **strict**    - This option requires all functions to run in ECMAScript 5's strict mode.
- [ ] **trailing**  - This option makes it an error to leave a trailing whitespace in your code. Trailing whitespaces can be source of nasty bugs with multi-line strings in JavaScript
## Relaxing Options
- [ ] **evil**      - This option suppresses warnings about the use of eval. The use of eval is discouraged because it can make your code vulnerable to various injection attacks and it makes it hard for JavaScript interpreter to do certain optimizations.
- [ ] **expr**      - This option suppresses warnings about the use of expressions where normally you would expect to see assignments or function calls. Most of the time, such code is a typo. However, it is not forbidden by the spec and that's why this warning is optional.
- [ ] **browser**   - This option defines globals exposed by modern browsers: all the way from good old document and navigator to the HTML5 FileReader and other new developments in the browser world.

**Comment by hpneo** [comment]
Closed because now we'll use ESLint that extends [`airbnb-base`](https://github.com/airbnb/javascript) with some custom rules defined.
