### ISSUE TITLE
filter marker

### ISSUE THREAD

**Issue by Sara-smith** [hpneo/gmaps#277]
hi.
first , sorry for my bad english.
how do i filter marker&group and update markerClustring in map?
i want  search marker and see result in map.

filtering group like this :
http://www.pittss.lv/jquery/gomap/solutions/group.html

and show/hide marker like this :
http://www.pittss.lv/jquery/gomap/examples/marker_showhide.php

**Comment by Frlawer** [comment]
someone?

**Comment by hpneo** [comment]
You can filter markers using https://github.com/hpneo/gmaps.extensions (check `gmaps.markerFilter.js`).

Also, GMaps supports Marker Clusterer (check `examples/marker_clusterer.html` in this repo). You will need to manually update the Clusterer to showing/hidding markers.

**Comment by xzegga** [comment]
how i can set visible on the map only the markers returned in filtered_markers with gmaps.markerFilter  plugin?

Best

**Comment by Frlawer** [comment]
Check
https://github.com/hpneo/gmaps/issues/465
