### ISSUE TITLE
drawRoute() method fails when too many routes are drawn in a row

### ISSUE THREAD

**Issue by fgalan** [hpneo/gmaps#278]
It seems that `drawRoute()` method fails when too many routes are drawn in a row, without pause. For example, the following code fails for large `places` arrays (e.g. 35 elements). I have checked empirically in my system that only the 10 first routes are drawn.

```
map = new GMaps()
...
lat = lat0;
lng = lng0;
// places is an array of coords, e.g. places:= [[lat1, lng1], [lat2, lng2], ...]
for (i = 0; i < places.length ; i++) {
   map.drawRoute({
      origin: [lat, lng],
      destination: [places[i][0], places[i][1]],
      travelMode: 'driving',
      strokeColor: '#000000',
      strokeOpacity: 0.6,
      strokeWeight: 5
   });
   lat = places[i][0];
   lng = places[i][0];
};
```

I guess that this could be due to some internal buffer used in the GMap object, that "saturates", not accepting new routes in that situation.

The only workaround that I've found is to set an interval between `drawRoute()` invocations (using `setTimeout()`). I have empirically found that with an interval of 1 second routes are correctly drawn. However, this is a bad solution (e.g. drawing 35 routes takes 35 seconds).

I'm doing something wrong? Is this a known bug? Is there any better workaround?

Thanks!

**Comment by fgalan** [comment]
@hpneo could you elaborate on the reason to close this issue, please? (e.g. it has been already fixed, it is not an actual issue, report information is not enough, etc.). Thanks!

**Comment by hpneo** [comment]
Hi, I'm sorry for not responding this issue before. I closed a lot of issues this weekend because they didn't have a reply in months (or in this case, in years), which I'm really really sorry.

If you still have this problem let me know so I can reopen it.

**Comment by fgalan** [comment]
I think I spotted this when I was doing some testing.... nothing serious. However, it happened more than 3 years ago :) so I don't remember pretty well.

Thus, I think it can be left closed.

**Comment by dianaVidalC** [comment]
I wish they showed the answer.
