### ISSUE TITLE
document how to use with module loaders

### ISSUE THREAD

**Issue by petri** [hpneo/gmaps#281]
For example with requirejs. Specifying gmaps.js as a dependency is trivial, but how does gmaps.js expect to find the actual google maps js library it depends on? Keeping in mind that we want to load the google maps library asynchronously using the module loader, as well.

**Comment by davidmaneuver** [comment]
It has everything in place to use https://github.com/aerisweather/googlemaps-amd now.

**Comment by adambiggs** [comment]
@davidmaneuver the root issue should have been fixed as of #413, but AFAIK there isn't any mention of this functionality in the official docs yet.

**Comment by hpneo** [comment]
Added the info in the README, I don't know why I've seen this before :disappointed:
