### ISSUE TITLE
removeMarkers / removeMarker / collection of markers

### ISSUE THREAD

**Issue by maciekfreak** [hpneo/gmaps#303]
Is there any possibility to remove group of Markers?

var group1 = [{
        lat : '51.919438',
        lng : '19.145136'}]
var group2 = [{
        lat : '52.919438',
        lng : '19.145136'}]

map.addMarkers(group1)
map.addMarkers(group2)

How to remove group1 or setVisible = false to group1 ?

**Comment by albertojm** [comment]
Hi @hpneo I'm trying to do the same thing, as you said it had to be an array of google.maps.Marker objects, I did this:

`for (var i = 0; i < markers_data.length; i++) {
   old[i] = markers_data[i];
};`
`map.removeMarkers(old);`

markers_data being the objects that i added previously via:

`map.addMarkers(markers_data);`

And I can't get it to work, any hints?

**Comment by hpneo** [comment]
Hi @albertojm, is `markers_data` an array of plain objects or an array of `google.maps.Marker` objects? It needs to be the latter one.
