### ISSUE TITLE
Fail with HTML5 doctype

### ISSUE THREAD

**Issue by boldt** [hpneo/gmaps#305]
I searched quite long for a bug now. Here is my result:
- Using `<!DOCTYPE>`, gmaps works as expected.
  - An example: http://www.dennis-boldt.de/test/gmaps/test1.html
- Using `<!DOCTYPE html>`, gmaps does not work.
  - An example: http://www.dennis-boldt.de/test/gmaps/test2.html

tl;dr: gmap fails with the HTML5 doctype. Testes in Chrome and Firefox.

**Comment by Sohair63** [comment]
For my rails application `<!DOCTYPE html>` was not loading properly, but half page, adding this fixed my issue :) 
```html { height: 100% }
body { height: 100%; margin: 0; padding: 0 }```
