### ISSUE TITLE
Auto open contextmenu when zoom map

### ISSUE THREAD

**Issue by vtproduction** [hpneo/gmaps#307]
The problem is, when I create a marker, and set context menu to this marker. After opening/closing this context menu, then when the map is zoomed, the previous context menu is automatically open.

Anyone have solutions?  Thanks alot !

////////////////////////////////////////////////////////////////////
UPDATE: I just try to fix this bug by set listener to map:
- When zoom map: set context menu style to display: none !important
- When idle map: set context menu style to display: none

Its worked, but hope you will consider this issue in next update.

**Comment by panagiotisl** [comment]
Not sure why this is closed. If you check gmaps/examples/context_menu.html, after creating a marker and right clicking on it, zooming in or out exposes the marker's context menu.

Only the map context menu works fine.

**Comment by hpneo** [comment]
Thanks for noticing this. It's fixed no in 0.4.19
