### ISSUE TITLE
Map not load properly

### ISSUE THREAD

**Issue by Frlawer** [hpneo/gmaps#309]
![maps](https://cloud.githubusercontent.com/assets/1776693/2698811/c90155d8-c3fe-11e3-88b2-176bea6ee25d.jpg)
I have problems loading the map shows me this way.
could give me some clue on how to fix this problem?

**Comment by akoper** [comment]
I have this problem, too, where the Google map tiles do not fill the #map div

![gmap screenshot](https://cloud.githubusercontent.com/assets/892578/5890364/2a17c792-a425-11e4-840c-769842e9309e.jpg)

**Comment by hpneo** [comment]
Hi, use `refresh()`

**Comment by akoper** [comment]
Hi Gustavo, my code is below.  It is not clear to me where or how to "use refresh()."

```
<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script type="text/javascript" src="../js/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="../js/gmaps.js"></script>
	<script type="text/javascript">
		var map;

		$("document").ready(function() {
			map = new GMaps({
				div : '#map',
				lat : 42.3314,
				lng : -83.0458
			});

			GMaps.geolocate({
				success : function(position) {
					map.setCenter(position.coords.latitude, position.coords.longitude);
				},
				error : function(error) {
					alert('Geolocation failed: ' + error.message);
				},
				not_supported : function() {
					alert("Your browser does not support geolocation");
				}
			});
			
              //allow user to click on map to select location
			GMaps.on('click', map.map, function(event) {
				var lat = event.latLng.lat();
				var lng = event.latLng.lng();

				$('#lat').val(lat);
				$('#lon').val(lng);
			});
			
		});
	</script>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Click on map to pick the latitude and longitude of task location</h4>
      </div>
      <div class="modal-body">
      	<div id="map" style="width:560px !important; height:400px !important" data-load='resizeMap'></div>
      </div>
    </div>
  </div>
</div><!-- modal end -->
```

**Comment by hpneo** [comment]
You need to use the __refresh__ method __after__ showing the modal, since the Google Maps map will be created *before* the modal is shown. When a HTML element is hidden (as your modal), the browser can't know its dimensions, so Google Maps. With `map.refresh()`, Google Maps redraws the map using the current dimensions of its container, which is visible now.

**Comment by akoper** [comment]
I added this to the JavaScript file in my application

```
	$("#mapModal").click(function() {
		window.setTimeout(map.refresh(), 500);		
	});
```
When a user clicks on the hyperlink to make the modal containing the Google map visible, there is a slight delay, the refresh method is run on map, and it (re-)renders the map full-size in the map div.  This works.

**Comment by oaattia** [comment]
Hello i'm facing the same problem here but i can't solve this problem really .. 

Could you please help me in this issue ? 

Please find my code fiddle 

https://jsfiddle.net/apjhytdL/

**Comment by akoper** [comment]
oaattia, My hyperlink that launches the overlay/modal that contains the Google map has an id=mapModel.  I am using jQuery.  In my JS file, I have the following lines that force it to refresh microseconds after it is launched so that the map 100% fills up the now-created div:

	//onclick of modal hyperlink, after modal is visible and map div is full size,
	//after 500ms delay, resize/refresh map so it rerenders and fills up entire map div
	$("#mapModal").click(function() {
		function mapRefresh() {
			map.refresh();
		}
		
		window.setTimeout(mapRefresh, 500);		
	});
about:blank
