### ISSUE TITLE
Using GMaps with Twitter Bootstrap 3

### ISSUE THREAD

**Issue by CirrusTech** [hpneo/gmaps#343]
Hi guys.

I'm facing the map redrawing issue with my maps.

The map is included in a collapsible section which is toggled with a button. When the button is pressed and the section slides down, the map is displayed but very strangely (only part of the container is filled).

I've tried to call the refresh() property but it's made no difference (I don't actually know if it's doing anything).

Anyone else managed to get the GMaps working inside of a collapsible section or with Bootstrap?

Thanks.
Ed

**Comment by makshh** [comment]
Maybe it's too late but you have to load the map once only when you click that button.

For example:

```
$('.button').one(click' function () {
  new GMaps({
    div: '#map',
    lat: -12.043333,
    lng: -77.028333
  });
};
```
