### ISSUE TITLE
Polyline with infowindow

### ISSUE THREAD

**Issue by daniel7856566** [hpneo/gmaps#353]
Hi all, please help me with one little problem.  I use gmap.js and polyline function - http://hpneo.github.io/gmaps/examples/polylines.html. Question: i need polyline wiht infowindow. When i click to line = display some HTML content (simmilar marker with infowindow)

Thank for resposne

**Comment by daniel7856566** [comment]
Nobody help me? How i make infowindow after click on polyline or polygon? some JSFIDDLE example?
Thanks for all

**Comment by hpneo** [comment]
Hi, I'm so sorry for not seeing this post before. You can show an InfoWindow using this code:

```javascript
var infoWindow = new google.maps.InfoWindow({
  content: 'you clicked a polyline'
});

map.drawPolyline({
  path: path,
  strokeColor: '#131540',
  strokeOpacity: 0.6,
  strokeWeight: 6,
  click: function(clickEvent) {
    var position = clickEvent.latLng;

    infoWindow.setPosition(position);
    infoWindow.open(map.map);
  }
});
```
