### ISSUE TITLE
marker clusterer help

### ISSUE THREAD

**Issue by morrow95** [hpneo/gmaps#355]
Have it working, but also trying to set options for the it.  Current code is : 

```
//create the map
map = new GMaps({
	el: '#map_canvas_main',
	lat: response.results[0].lat,
	lng: response.results[0].lng,
	zoom: 5,
	description: ' tracks: click to show',
	maxZoom: 15,
	panControl: false,
	markerClusterer: function(map) {
		return new MarkerClusterer(map);
	}
});

//loop through array
for(var i = 0; i < response.results.length; i++)
{
	//add marker
	map.addMarker({
		lat: response.results[i].lat,
		lng: response.results[i].lng,
		icon: '/custom/plugins/gmaps/images/marker-red.png',
		title: response.results[i].ip_address,
		infoWindow: {
		  content: '<p>'+response.results[i].ip_address+'</p>'
		}
	}); 
}
```

I want to be able to do something like : 

```
var markerClustererOptions = {   
    description: ' some tooltip text over the cluster,  
    maxZoom: 12,  
    gridSize: 50  
};  
var markerClusterer = new MarkerClusterer(map, markers, markerClustererOptions);
```

'description' is a valid option in the markercluster js - is there any way to set options on it and still use it with gmaps?  Everything I have tried does not seem to be recognizing them...

Secondly, I have come across the issue where I will have multiple markers in the same exact location (lat/lng), but in reality are different markers.  I came across a few solutions, namely, http://stackoverflow.com/questions/3548920/google-maps-api-v3-multiple-markers-on-exact-same-spot, however, the same problem mentioned earlier arises due to the way clusters are set with gmaps... any way around this to be able to get these solutions working?

**Comment by davidwillianx** [comment]
minha solução: 
`var map = new Gmaps({
  el: '#map',
  lat: default.lat,
  lng: default.lng,
  markerClusterer: function(map){
     var markerClusterer = new MarkerClusterer(map, [], {
       gridSize: 12,
       zoomOnClick: false
     });

      //*native google maps event 
      google.maps.event.addListerner(makerClusterer, 'clusterclick', function(cluster){
           return multiChoice(cluster);
      }
  }
});

 function multiChoice(cluster){
            if (clickedCluster.getMarkers().length > 1)
        {
            var markers = clickedCluster.getMarkers();
            var infoWindow = new google.maps.InfoWindow();
            infoWindow.setContent('<span class="badge">'+clickedCluster.getMarkers().length+'      markers</span>');
            infoWindow.setPosition(clickedCluster.getMarkers()[0].getPosition());

            infoWindow.open(map.map, clickedCluster);
            return false;
        }
        return true;
 }


`
