### ISSUE TITLE
Get address by coordinates

### ISSUE THREAD

**Issue by olanchuy** [hpneo/gmaps#361]
Hi,

Is geocoding reverse supported by gmaps? I would like to get the address using the coordinates. Thanks

**Comment by conor909** [comment]
@hpneo so your saying put the coordinates into the `address` option?

**Comment by conor909** [comment]
So I worked it out by guessing but I think the docs need to be updated.
```javascript
GMaps.geocode({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
            callback: function(results, status) {
                if (status == 'OK') {
                    console.log(results);
                }
            }
        });
```

**Comment by hpneo** [comment]
@conor909 yes, sorry about that. I'm working on a better documentation.
