### ISSUE TITLE
Error Too much recursions

### ISSUE THREAD

**Issue by batzidi** [hpneo/gmaps#366]
Hello.
I setup a page to show the error: http://cloud.bzimg.com/gmaps

The Problem:
When I try to resize the window and set the Center again for the map it's going into recurstion and eventually breaks the map.
Chrome just shows error in the console while Firefox shows the exact error: Too much recursions. The line  on which the error occurs is different everytime, but so far it repeatly says lines: 13, 14, 17

Every suggestion or advise is welcome.
Thank you

**Comment by krishunt** [comment]
How does this solve the recursion problem? Using that same code, Chrome still locks up for me with 100% CPU usage.

**Comment by hpneo** [comment]
Could you please post your code here?

**Comment by amenadiel** [comment]
@batzidi you shouldn't try to access map center's properties ( lat and lng ) directly. The key keeps changing and probably 'k' and 'B' doesn't mean anything at this point. Always try to use the getters.

```js
var lat = map.getCenter().lat(),
    lng = map.getCenter().lng();
```

**Comment by krishunt** [comment]
Felipe, that fixed it! The code that works is:

<code>
$(window).resize(function() {
var lat = map.getCenter().lat(),
    lng = map.getCenter().lng();
map.refresh();
map.setCenter(lat, lng);
});
</code>

Thank you very much!

**Comment by batzidi** [comment]
@amenadiel You're right! This is what I am using right now. But forgot to put a comment about it.

**Comment by amenadiel** [comment]
Cheers then @batzidi
