### ISSUE TITLE
Gmaps and the use of tabbed content

### ISSUE THREAD

**Issue by appeltje** [hpneo/gmaps#369]
Is it possible to refresh gmaps when used in a tabbed content? In other words when clicked on a certain tab where gmaps is to be shown is possible to refresh when clicked.

Now gmaps is not shown properly

kind regards,
Appeltje

**Comment by gkimpson** [comment]
Did you get this to work? I am trying something with jQuery UI Accordion and having no joy

**Comment by rawsonkara** [comment]
attach your own event listener, do not edit the minimized source code.. see here

http://www.w3schools.com/js/js_htmldom_eventlistener.asp

you might need to destroy the map and recreate it when its container's display is set to something other then none;

also try to put your refresh into a setTimeout which will pop this call ontop of your event stack. anyways just some ideas. 

i get around all of this by dynamically changing the height of the map to 0 rather then to set its display to none. which i believe is how accordion content might be working. Again just some ideas :)
