### ISSUE TITLE
GetRoutes issue

### ISSUE THREAD

**Issue by zbychuk** [hpneo/gmaps#373]
getRoutes when calling callback passes self.routes which may contain routes from previous calls, I would suggest to pass result.routes as self.routes are anyway available via map variable which was set to new GMaps.

**Comment by Ritikesh** [comment]
Thanks this helped me. Been breaking my head on this one for a long time now.

**Comment by Jafo232** [comment]
Will this bug ever be fixed?  I basically have to reinstantiate the Gmaps every time I call this to get different information on different legs of a trip.

**Comment by Jafo232** [comment]
I can confirm that zbychuk's suggestion works well.

**Comment by hpneo** [comment]
Sorry for the delay. The callback now passes a new array containing the requested routes only.
