### ISSUE TITLE
Marker with Label

### ISSUE THREAD

**Issue by kashifali2007** [hpneo/gmaps#376]
Hello
Kindly guide me, how to add Marker with label on the map.

**Comment by rustyfb24** [comment]
Hi,
Is there anyone who have used MarkersWithLabel. I used it with this code
the marker is showing but not the Label.

```javascript
var marker = map.addMarker({
      lat: parseFloat(markers[i].lat),
      lng: parseFloat(markers[i].lng),
      title: markers[i].plateno,
      markerWithLabel: function(marker){  
           return new MarkerWithLabel({
               labelContent: markers[i].plateno,
               labelAnchor: new google.maps.Point(22, 0)
       });
    }
});

**Comment by oshanz** [comment]
i am using this
http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.9/examples/basic.html
