### ISSUE TITLE
How can I remove one specific polyline

### ISSUE THREAD

**Issue by johnsh** [hpneo/gmaps#379]
How can I remove one specific polyline, I don't want run the method "removerPolylines()".

For example.

removePolyline("id_specific_o_reference.")

Or update one specific path

Sorry my english no is very good

Thank you

**Comment by hpneo** [comment]
Hi, you need to use `removePolyline`, passing a polyline object as parameter. You can access the map's polylines with `map.polylines` property.

**Comment by johnsh** [comment]
Oh, thank you, I'll try
