### ISSUE TITLE
Readme HTML example is incomplete and broken

### ISSUE THREAD

**Issue by tobozo** [hpneo/gmaps#380]
The HTML example in the Readme.md file is missing the script that loads jQuery from the CDN, or instruction to add it manually.

Milestone 0.2 claims "Removed jQuery dependency" but it was probably restored in a later version, and is not claimed.

Current version of gmap.js has references to the $ object, and the example won't work as is.

Excellent work anyway, definately adopting this project :-)

**Comment by droidenator** [comment]
Hm. Are you sure that jQuery is required? I just checked gmap.js and the only reference I find to jQuery is here on lines 124-125. Unless I missed something, it doesn't look like jQuery is required to use gmap.js. 

```javascript
  if ('jQuery' in this && context) {
    element = $('#' + id, context)[0];
  } else {
    element = document.getElementById(id);
  };
```

That being said, I do see examples found [here](http://hpneo.github.io/gmaps/examples.html) that
do use jQuery functions. Is this the example that you're referring to?

**Comment by hpneo** [comment]
Hi, I've re-created one of those examples here: http://codepicnic.com/bites/map-types.

As you can see, it doesn't use jQuery.
