### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'prototype' of undefined 

### ISSUE THREAD

**Issue by kashifnaseer** [hpneo/gmaps#382]
I'm getting below mentioned error when i try to include a gmaps.js file in Rails 4 application. 

```
 Uncaught TypeError: Cannot read property 'prototype' of undefined active_admin.js:18
 (anonymous function) active_admin.js:18
 (anonymous function) active_admin.js:17
 (anonymous function)
```

I downloaded the Google api from http://maps.google.com/maps/api/js?sensor=true into my local file and included it first. But its not working. I kept the both files in assets/javascipts path. 

```
 //= require google_map_api
 //= require gmaps
```

I'm using:

Rails 4.1.7
ruby 2.1.3p242 

I tried
https://github.com/hpneo/gmaps/issues/200
https://github.com/hpneo/gmaps/issues/126
but no luck

**Comment by amenadiel** [comment]
You can't use a local version of google maps api script. You can cache the loader script for a few minutes if you care to build a proxy, but it won't work for long. Endpoints keep changing, and parts of the internal requests you make to google carry data that is unique for your session.

What's wrong with using google's provided url?
