### ISSUE TITLE
Titanium

### ISSUE THREAD

**Issue by vanderleisp** [hpneo/gmaps#383]
is there something done together with the Titanium tool ??
I'm starting to do some tests and almost all the examples works well there, but the JSON with Foursquare isn't working.
Basically page loads without even the map showing up, and nothing shows up from the Foursquare side.
I'll dig a little more on this but if you guys had already did some integration with Titanium this would help.
By the way, thanks for the great solution.

Vanderlei

**Comment by vanderleisp** [comment]
problem is that all files not local must be using "http:" instead of only something like //ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js 
and this problem also happens on browsers.

**Comment by hpneo** [comment]
As far as I know, you only need to add the protocol (like `http:` or `https:`) to the URLs.
