### ISSUE TITLE
Draw Route Function with Custom Route

### ISSUE THREAD

**Issue by SaadAhmed13** [hpneo/gmaps#384]
Hi,
I am currently using draw route function draw a route between two points (e.g A and B). What i'd like to do is define a custom route so if i have some points between two routes (A and B) I'd like to define them like so:
drawRoute(A,B)->with(Point1,Point2,...)

Is it currently possible to do this using gmaps wrapper for Google Maps Api?

If it is, please do post a sample.

Thank you

**Comment by hpneo** [comment]
Hi, check this: https://github.com/hpneo/gmaps/issues/46
