### ISSUE TITLE
how to change infowindow style

### ISSUE THREAD

**Issue by biju001** [hpneo/gmaps#385]
i want to change info width height, width and some css. currently sometime some marker info show properly and some maker info show scroll even that info not that much big . i think if i can set min-height and min-width then may be problem will be solve. or is there any way to info fit properly without scroll.

my info html . like have BR, H2. H4. strong etc

**Comment by hpneo** [comment]
Hi, you only can set the max-width for infoWindows: https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions

If you need a custom InfoWindow you may use overlays: http://hpneo.github.io/gmaps/examples/overlays.html

**Comment by biju001** [comment]
thank u so much for your reply. i am trying...
