### ISSUE TITLE
strange loop in the code 

### ISSUE THREAD

**Issue by beshoo** [hpneo/gmaps#387]
Dear author,
Thank you for this wonderful script  , but i have a strange bug with it 
here is my code : http://pastebin.com/Z2ew6Nmy

it generate google map with markerClusterer!

But if you open this page http://spyon.mobi/map.htm 

and look to the console you will see some thing strange , ny code pass all log point ... but after 3 seconds a strange loop start!

**Comment by hpneo** [comment]
Hi, please try replacing `latlong['B']` with `latlong.lat()` and `latlong['k']` with `latlong.lng()`.

**Comment by beshoo** [comment]
thank you for fast reply , it works BUt it dos not return what i need , it seem google change some vars , have a look with me :

what i need is to get :

jf {k: 39.157938285, D: 21.54135079999992, toString: function, j: function, equals: function…}

K and D from this JSON code which is the center calculation od the Loacation points that i have in the array !

When i replace the latlong['B'] with latlong['D'] it works just fine , 

check it out 
https://spyon.mobi/map.htm

how can i reach the latlong even if google change some thing?

**Comment by hpneo** [comment]
Yes. You must use `lat` and `lng` methods, not `k` or `D`.
