### ISSUE TITLE
how to using the plugin on the same class ?

### ISSUE THREAD

**Issue by hamdan-mahran** [hpneo/gmaps#388]
Hi
Thanks very much for this awesome plugin,
i want to have many maps in the same page, without change class name or id,
for example : 
<pre>
$('.google-map').each(function(index) {
        // make it google map
});
</pre>
Because when i put class inside <b>el: '.google-map'</b> it give me error :(

Thanks

**Comment by hamdan-mahran** [comment]
Hi,
i find this way to make it,
This is my html :
<pr>
<div class="google_map"></div>
</pre>

This is my jQuery
<pre>
$(".google_map").each(function(index) {
			var con_index = index + 1;
			var id_name = "map" + con_index;
			$(this).attr('id', id_name);
			
			var map;
			map = new GMaps({
				el: '#'+id_name,
				lat: -12.043333,
				lng: -77.028333
			});
			//----------------------> locations request
			map.getElevations({
				locations : [
					[-12.040397656836609,-77.03373871559225], 
					[-12.050047116528843,-77.02448169303511],  
					[-12.044804866577001,-77.02154422636042]
				],
				callback : function (result, status){
					if (status == google.maps.ElevationStatus.OK) {
						for (var i in result){
							map.addMarker({
								lat: result[i].location.lat(),
								lng: result[i].location.lng(),
								title: 'Marker with InfoWindow',
								infoWindow: {
									content: '<p>The elevation is '+result[i].elevation+' in meters</p>'
								}
							});
						}
					}
				}
			}); 
		});
</pre>

it works good now

**Comment by hpneo** [comment]
Hi, you can pass the HTML element instead a string selector:

```javascript
$(".google_map").each(function(index, element) {
  var map = new GMaps({
    el: element
  });
  // ...
}
```

**Comment by hamdan-mahran** [comment]
Thanks very much @hpneo :)
Its forks good with your solution!
