### ISSUE TITLE
Draggable Directions

### ISSUE THREAD

**Issue by tkrause** [hpneo/gmaps#399]
Is there anyway right now to make directions draggable and update the route? This is available in the official Maps API V3. If not this would make a great addition.

**Comment by hpneo** [comment]
Hi, could you provide me the link from the Maps API page?

**Comment by tkrause** [comment]
Sure thing!

https://developers.google.com/maps/documentation/javascript/examples/directions-draggable

**Comment by cssjockey** [comment]
Hi, any update on this?

**Comment by hpneo** [comment]
Hi, I added this feature in the 0.4.22 version. Check a demo here: https://github.com/hpneo/gmaps/blob/master/examples/render_directions.html

Sorry for the delay :disappointed:
