### ISSUE TITLE
How to call the marker.click function from outside the map?

### ISSUE THREAD

**Issue by neotamizhan** [hpneo/gmaps#40]
Hi,

This is not an issue, just a query. 

I am building a map with several markers (and infoWindows). Now when a marker is clicked, the corresponding infoWindow is displayed (with proper screen positioning). I want to do the same when a place is selected from a drop down list. How can I hook into the google.maps.Marker's click event? 

I can call, "map.hideInfoWindows()" followed by "marker[i].infoWindow.open". This does show the info window. But the displayed widow is not centered. And also it does not have any of the events associated with it. I cannot close this window using the "close" button. 

Could you please help me with this? 

Siddharth

**Comment by zia-qamar** [comment]
How to click map location instead of marker

**Comment by kamleshwebtech** [comment]
> Hi,
> 
> The issue was solved. Calling the marker's click event using the google.maps.event.trigger method solved the issue.
> 
> ```js
>  var ourMarker = getMarker(title)
>  google.maps.event.trigger(ourMarker, 'click');
> ```

This does not work in clustered markers (one of the group markers) situation. Please share suggestion if you have. Thanks.

**Comment by hpneo** [comment]
Hi @kamleshwebtech you'll probably need to attach your click events into the marker cluster, since the markers aren't in the map when they grouped.

Check this example: https://googlemaps.github.io/v3-utility-library/packages/markerclustererplus/examples/events_example.html

**Comment by kavishatalsania** [comment]
Hi @kamleshwebtech  and @hpneo , I am still not able to trigger click event on clustered markers. Can you share example code if possible?

**Comment by kamleshwebtech** [comment]
@kavishatalsania  Please check this demo
https://www.mrhandyman.com/local-handyman-service

**Comment by kavishatalsania** [comment]
@kamleshwebtech Thank you sharing this link. I want to open a info window of a marker which is inside map cluster. For other marker `google.maps.event.trigger(ourMarker, 'click');` is working, but if marker is inside cluster then it is not working. Can you share the code to make it work?

**Comment by hpneo** [comment]
@kavishatalsania do you have a working example where I can debug?

**Comment by kavishatalsania** [comment]
@hpneo This is the working example: [](url) https://codesandbox.io/s/new-bird-8fp0q?file=/src/index.ts

On line 58, I triggered event for marker[0] which is not inside any marker cluster. That is why it it working as expected.

Please change line number 58 to `google.maps.event.trigger(markers[1], "click");` . That will not work because it is inside marker cluster.

**Comment by hpneo** [comment]
@kavishatalsania I'm sorry but that example doesn't event use GMaps. If you are using GMaps with MarkerClusterer I recommend you to create a new issue.
