### ISSUE TITLE
drawPolygon issue

### ISSUE THREAD

**Issue by nlybe** [hpneo/gmaps#408]
I replace 0.4.15 with 0.4.17 and the following doesn't seem to work. 
On 0.4.15 it works fine

    map_polygon = map.drawPolygon({
                    paths: path, // pre-defined polygon shape
                    index: pindex,
                    strokeColor: '#BBD8E9',
                    editable: true,
                    draggable: true,
                    strokeOpacity: 1,
                    strokeWeight: 3,
                    fillColor: '#BBD8E9',
                    fillOpacity: 0.7
            });

**Comment by hpneo** [comment]
Could you please post a demo with your code? Or the error log from the Dev Tools (or Firebug)

**Comment by nlybe** [comment]
You can try it at http://dev.agoramap.com/drawonmaps/draw.php. Select "Polygon" and and click on "Add polygon" button. It should draw a polygon on map. 
If I use 0.4.15, it works

**Comment by hpneo** [comment]
I pushed a new version that might fix this bug. Please tell me if it works.

**Comment by nlybe** [comment]
Yes, it works fine
Thanks

**Comment by hpneo** [comment]
Cool, thanks for the bug report
