### ISSUE TITLE
Adding Marker Tracking

### ISSUE THREAD

**Issue by analog81** [hpneo/gmaps#409]
Hi,

Does anyone know how to add Analytics tracking to a map with multiple markers? I'm trying to figure out which location is being clicked on the most. Also, I'm trying to track a mailto link inside the info window on click. I'm new and your help would be greatly appreciated. Thanks.

**Comment by hpneo** [comment]
You can track the click event of the markers (check this example: http://hpneo.github.io/gmaps/examples/markers.html). You need to read about the Google Analytics JS API.

About mailto links, you could be same as the markers, but adding an id attribute to the mailto link and using jQuery to capture the click event for that id.
