### ISSUE TITLE
Additional informations passed to InfoWindow

### ISSUE THREAD

**Issue by A35G** [hpneo/gmaps#411]
Hi all,
Hi @hpneo ,
there is an opportunity to pass additional information, within the InfoWindow, how you can do that through events?

It might be interesting to manage them well in there.

**Comment by hpneo** [comment]
I'm not sure what you mean. Right now you can attach an infoWindow to a marker using the `infoWindow` option in `addMarker()`, but only accepts the `google.maps.InfoWindow` properties.

**Comment by A35G** [comment]
If I use the next code, I have possibility to specify and to show additional information by events;
```javascript
        map.addMarker({
            lat: 41.917818,
            lng: 12.492010,
            details: {
                author: 'Test'
            },
            click: function (e) {
                alert(e.details.author);
            }
        });
```
it's possible to integrate these details also in the content of the infoWindow?

**Comment by hpneo** [comment]
You need to update manually the content of the InfoWindow in the `click` event (or any other place). I think you can use `e.infoWindow.setContent("your new content")`.

**Comment by A35G** [comment]
Thanks @hpneo, in these days, with so many thoughts in my head, I did not think this very simple solution.

Thanks a lot.

**Comment by hpneo** [comment]
You're welcome!
