### ISSUE TITLE
is gmaps.js compatible with Google Maps places library?

### ISSUE THREAD

**Issue by webkod3r** [hpneo/gmaps#414]
Hi, I want use this plugin with google maps places libary. I tried to use this API call
`http://maps.google.com/maps/api/js?sensor=true&v=3&libraries=places` but when maps load I got the following error: `Uncaught TypeError: Cannot read property 'offsetWidth' of null`

Is this plugin works with Google Maps v3?
Anyone have tested with Places library?

Thanks in advance.
WK

**Comment by hpneo** [comment]
Please post your code. I didn't tried the Places library but I did load other libraries (like geometry), so it should work fine.

**Comment by webkod3r** [comment]
Sorry for my late answer but I have to solve the problem without this plugin. Also I'm interested to solve this problem to use this plugin in future.

``` html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Demo gmaps.js Places</title>
  <style type="text/css">
    #map{
      width: 500px;
      height: 400px;
    }
  </style>
</head>
<body>

<!-- map container -->
<div id="map"></div>

<!-- Scripts -->
<script type="text/javascript" src="//localhost/libraries/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true&libraries=places"></script>
<script type="text/javascript" src="js/gmaps/gmaps.min.js"></script>
<script type="text/javascript">
  var map;
  (function ($) {

    map = new GMaps({
      el: '#map',
      lat: 41.395374,
      lng: 2.161956,
      zoomControl : true,
      zoomControlOpt: {
        style : 'SMALL',
        position: 'TOP_LEFT'
      },
      panControl : false,
      streetViewControl : false,
      mapTypeControl: false,
      overviewMapControl: false
    });

    var infoWindow = new google.maps.InfoWindow();
    var service = new google.maps.places.PlacesService(map);

  })(window.jQuery);
</script>
</body>
</html>
```

Only with this I got the following error

`Uncaught TypeError: this.j[Xb] is not a function`

Thanks in advance
WK

**Comment by hpneo** [comment]
I found the bug. When you use `PlacesService` you need to pass the `google.maps.Map` instance (`map.map`), not the GMaps instance (`map`): https://codepicnic.com/bites/gmaps-js-issue-414

**Comment by webkod3r** [comment]
Thanks a lot for your help!!!
