### ISSUE TITLE
Help in implementing multiple marker with infoWindow on them

### ISSUE THREAD

**Issue by amitRanjan** [hpneo/gmaps#416]
I am pulling data from my database as json. I have fields like Latitude,Longitude, ImagePath, Description, Title etc. coming. Now I want Lat and Long to be used for markers and the rest things like name,image to be displayed in their respective infoWindow with a hyperlink.
Is this possible. I am struggling with your example on using Json. Please help

**Comment by hpneo** [comment]
You can create a infoWindow for each one of your markers, and store that data in the `details` property of `addMarker`:

```javascript
map.addMarker({
  lat: latitude,
  lng: longitude,
  details: {
    imagePath: point.imagePath,
    title: point.title,
    description: point.description
  },
  infoWindow: {
    content: '<h2>' + point.title + '</h2><p>' + point.description + '</p>'
  }
})
```
