### ISSUE TITLE
error on 'working with json' example page

### ISSUE THREAD

**Issue by mgenev** [hpneo/gmaps#418]
This page https://hpneo.github.io/gmaps/examples/json.html  gives this error:

> Mixed Content: The page at 'https://hpneo.github.io/gmaps/examples/json.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://coffeemaker.herokuapp.com/foursquare.json?q[near]=Lima,%20PE&q[query]=Ceviche'. This request has been blocked; the content must be served over HTTPS.

No markers or anything else shows on the map...

**Comment by hpneo** [comment]
Fixed in #422
