### ISSUE TITLE
Help on reverse geofencing alerting on enter not exit.

### ISSUE THREAD

**Issue by pmercadohn** [hpneo/gmaps#419]
Hi, I will like to get some ideas or help if available on making the geofence to alert on entry of markers, I will also like to know hoy to use the drawing mangers tools to draw the poligon, circle or square to build the fends insted of coordinates array given.

Thanks

**Comment by hpneo** [comment]
I'm not familiar with the drawing tools but you can check if a marker is inside or outside using the method `checkGeofence(latitude, longitude, polygon_circle_or_rectangle)`. It returns `true` if the point is inside, and `false` if not.

You can check for alerts using `position_changed` event in markers. For now, you need to do this for every marker in your map.
