### ISSUE TITLE
How to remove markers, one or all?

### ISSUE THREAD

**Issue by mykhas** [hpneo/gmaps#42]
I cann't find it in examples... Any ideas?

**Comment by qermezkon** [comment]
`function ShowMap(val)
{
    var map;
    var path = [];
    map = new GMaps({
        div: '#Map',
        address: $('#SearchInMap').val(),
        lat: 31.2905559,
        lng: 48.625299,
        click: function (e) {
            path.push(e.latLng);
            console.log(path);

            map.addMarker({
                lat: e.latLng.lat(),
                lng: e.latLng.lng(),
                title: path.length.toString(),
                click: function (e) {
                    path.pop(e.latLng)
                    console.log(path);
                    map.removeMarker(e);
                },
                //infoWindow: {
                //    content: '<p>HTML Content</p>'
                //}
            });
        },
        callback: function (results, status) {
            if (status == 'OK') {
                var latlng = results[0].geometry.location;
                map.setCenter(latlng.lat(), latlng.lng());
                map.addMarker({
                    lat: latlng.lat(),
                    lng: latlng.lng()
                });
            }
        }
    });
}`

**Comment by codetrash** [comment]
One marker can be deleted 
```
..
infoWindow: { 
     content :  '<br><button class="remove-marker" data-marker-index="'+marker_index+'">Delete marker</button>'
}
```
like this (if u r using jQuery)
```
//use live click
    $(document).on("click", ".remove-marker", function(e) {
        e.preventDefault();
        var id = $(this).data("marker-index");
        console.log("deleteing marker ", id);

        map.removeMarker(map.markers[id]);
  });

```

@mykhas

**Comment by codetrash** [comment]
remove single marker
```
map.addMarker({
            lat: lat,
            lng: lng,
            title: 'Marker #' + marker_index,
            draggable: true,
            infoWindow: {
                content : '[lat, lang] : [' + lat + ',' + lng + ']'
                          + '<br><button class="btn btn-default remove-marker" data-marker-lat="'+lat+'" data-marker-lng="'+lng+'">Delete marker</button>'
            },
            dragend: function (m) {
                console.log(marker_index);
                console.log(m.latLng.lat())
            }
        });
```

```
//use live click
    $(document).on("click", ".remove-marker", function(e) {
        e.preventDefault();
        var lat = $(this).data("marker-lat");
        var lng = $(this).data("marker-lng");
        console.log("deleting marker ", lat, lng);
        $.each(map.markers, function(index, marker) {
            var m_lat = marker.getPosition().lat();
            var m_lng = marker.getPosition().lng();
            if (m_lat == lat && m_lng == lng) {
                map.removeMarker(map.markers[index]);
                return false;
            }
        });

    });
```

**Comment by alexisgodfroycc** [comment]
Ok
