### ISSUE TITLE
gmaps on CDNJS

### ISSUE THREAD

**Issue by craiglondon** [hpneo/gmaps#420]
Any update when the newer releases will be available on CDNJS?  Currently the most recent release is 0.4.12.

https://cdnjs.com/libraries/gmaps.js

**Comment by hpneo** [comment]
I didn't maintain that repo. I will update it in the next days, maybe the next week. So sorry, I'm really busy right now :disappointed:

**Comment by kevin-brown** [comment]
cdnjs now allows for auto-updating in [their package.json for gmaps.js](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/gmaps.js/package.json), you just need to add a pull request that adds the `autoupdate` key with your configuration. [Here is the one we use with Select2.](https://github.com/cdnjs/cdnjs/blob/38e17355e6e03ab54b9f63dfedb13061066608f0/ajax/libs/select2/package.json#L27-L35)

This should work for an autoupdate configuration for gmaps:

```json
"autoupdate": {
  "source": "git",
  "target": "git@github.com:hpneo/gmaps.git",
  "basePath": "",
  "files": [
    "*.js",
  ]
},
```

**Comment by hpneo** [comment]
Thank you @kevin-brown! You saved the day one more time :smiley:

**Comment by hpneo** [comment]
Thank you @kevin-brown! You saved the day one more time :smiley:

**Comment by kevin-brown** [comment]
cdnjs now has the newer versions, but the [version field is still set to 0.4.12](https://github.com/cdnjs/cdnjs/blob/31eee715a9ffa7a6e739da45b7083c0b0dcbc266/ajax/libs/gmaps.js/package.json#L4) in your `package.json`, so the default is still 0.4.12.

This should fix itself during the next gmaps release, so this can probably be closed off.

**Comment by hpneo** [comment]
Right, thanks @kevin-brown :)
