### ISSUE TITLE
Your demo site totally not working due to HTTPS

### ISSUE THREAD

**Issue by networksolution** [hpneo/gmaps#421]
Hi. Your site is running under HTTPS so almost all examples using JSON from Foursquare aren't working due to the "mixed active content" restriction (IE, FF, not tested Safari and Chrome).

Navigating your site with https://hpneo.github.io/gmaps/examples/json.html not working

Navigating with standard http://hpneo.github.io/gmaps/examples/json.html works.

Search engines are linking to the https version :(

**Comment by hpneo** [comment]
Fixed, thanks @kevin-brown !
