### ISSUE TITLE
how open marker, on click link?

### ISSUE THREAD

**Issue by Sky161** [hpneo/gmaps#426]
Hello. How open infoWindow marker, when clicked link on page?

**Comment by Bin4ry1337** [comment]
like this: 
```javascript 
    map.addMarker({
        lat: 63.998847,
        lng: 11.486882,
        title: 'Test',
        infoWindow:
        {
			content: 'Hello World'
		}
    });
```

**Comment by Sky161** [comment]
No. I mean, how to do so when you click on the external link to the page (without maps) opened infoWindow.
Example here http://jsfiddle.net/9vnpP/2/

**Comment by udithishara** [comment]
try passing a query from that main page to the map, then open info window according to that

**Comment by amenadiel** [comment]
The example you linked is manually instancing markers and infowindows. In gmaps, as @Bin4ry1337 said, adding a marker is a method of the map instance, and adding an infowindow is just an option when doing so.

If you declare 

```js
    map.addMarker({
        lat: 63.998847,
        lng: 11.486882,
        title: 'Test',
        infoWindow:
        {
            content: 'Hello World'
        }
    });
```

It implicitly instances a marker, which [is appended to `map.markers`](https://github.com/hpneo/gmaps/blob/master/lib/gmaps.markers.js#L126), and which implicitly contains an infowindow instance, which is referenced on its `infoWindow` property.

Therefore, calling

```js
var markerInstance = map.markers[0];
markerInstance.infoWindow.open(map, markerInstance);
```

will open the infowindow.

To attach a click listener to the DOM element you can use google maps domListener, jQuery listeners or attach onclick events like in your example.

**Comment by hpneo** [comment]
Thanks @amenadiel for this amazing explanation.

**Comment by ptep** [comment]
Is there a way to reference a marker by title, or detail attribute - instead of its placement in array? Thanks!

**Comment by ptep** [comment]
Scratch that.... just looping through looking for ID...

    $.each(map.markers, function(i,val) {
         if (map.markers[i].details.id == 'foo') {
              map.markers[i].infoWindow.open(map, map.markers[i]);
         }
    });
