### ISSUE TITLE
FIlter marker types

### ISSUE THREAD

**Issue by udithishara** [hpneo/gmaps#428]
Hello,

Is there a way to filter markers in gmap.js ?, i am able to do with other filter plugins but they're not compatible with this plugin :/

**Comment by hpneo** [comment]
Currently there's no way to filter markers in gmaps. You can use this code: https://github.com/hpneo/gmaps.extensions/blob/master/lib/gmaps.markerFilter.js (in alpha) to extend GMaps and use it this way:

```
map.markerFilter(function() {
  return this.category_id === 7;
});
```

**Comment by udithishara** [comment]
For now i solved my issue using jquery-ui-map plugin, but it looks like it's abandoned long time ago, so i'll give this a try, Thank you @hpneo
