### ISSUE TITLE
Open infoWindow on mouseover / hover

### ISSUE THREAD

**Issue by mgntrn** [hpneo/gmaps#429]
Hi,

I'm trying to open the infoWindow on mouseover. I found this solution, but it doesn't work: http://www.widecodes.com/CzVqegPWWV/gmapsjs-mouseover-open-infowindow.html. The mouseover event is triggers onclick and sometimes at random when I hover around the marker, but not on the marker itself.

I also tried to add an event listener, but this also doesn't work. Does someone have a solution?

**Comment by hpneo** [comment]
Check this example: http://jsfiddle.net/9ym3htwq/

**Comment by mgntrn** [comment]
Thanks for your reply. In the fiddle behavior is as expected, but when I use exactly this code in a stand-alone file, there is something wrong: http://mgntrn.nl/gmaps.html. As you can see, the mouseover event triggers when I hover just left of the marker, not ón the marker like in the fiddle. What did I do wrong here?

**Comment by mgntrn** [comment]
Okay, things are getting weirder. I'm using FireFox, but in Chrome everything is fine. How come the behavior of exactly the same code (from the fiddle) is different in one and the same browser (FireFox)?

**Comment by hpneo** [comment]
You're welcome, I'm gonna add this issue to the Tips page.
