### ISSUE TITLE
How to lock the map on scroll?

### ISSUE THREAD

**Issue by carlosmigel** [hpneo/gmaps#434]
Hey. :) When I scroll over the map, the map either zooms in or out, depending where are you going, up or down. How could I lock this option, so that if the cursor is on the map, you can't zoom it in or out with the mouse-wheel, but only zoom in or out with the buttons on the map side.

**Comment by ziga-miklic** [comment]
Hey, set the `scrollwheel` option to `false` next to other GMaps properties. Example:

````javascript
map = new GMaps({
   /* Other options */
   scrollwheel: false,
});
````
