### ISSUE TITLE
need to componentRestrictions to two countries

### ISSUE THREAD

**Issue by ecomgolive** [hpneo/gmaps#435]
Hi,

I am looking for a way to use the componentRestrictions function for just two countries, at the moment I have componentRestrictions: { country : "ie"} which works fine but I also want to include Northern Ireland which i thought would be componentRestrictions: { country: ["ie", "ni"] } this solution does not work,

Any Ideas ??

**Comment by hpneo** [comment]
It seems to be "impossible" according [this comment](https://code.google.com/p/gmaps-api-issues/issues/detail?id=4233#c145):

> Hi to all,
> 
> Have just had a comment from Google via a Maps-For-Work request for this feature:
> 
> "I am sorry to tell you that given the current backend, there is no plan to implement this feature."
> 
> I guess we'll have to wait for them to update the backend then...

However, you can do several requests, according [this post in SO](http://stackoverflow.com/questions/26753846/fill-google-maps-autocomplete-with-prediction-results/26886685#26886685)
