### ISSUE TITLE
InfoWindow onClick drawOverlay

### ISSUE THREAD

**Issue by knapeto** [hpneo/gmaps#437]
Hi,

any help with infoWindow onClick drawOverlay?

I have svg icons and I need rotation. Markers are very bad solution for my issue. So I created drawOverlay and rotation image svg here. I really need onClick show infoWindow.

Thanks for any advice!

**Comment by hpneo** [comment]
Hi, can you post your code in jsfiddle?

**Comment by knapeto** [comment]
Thanks for your help.

https://jsfiddle.net/xUUxn/2161/

**Comment by hpneo** [comment]
For now I can't be done the way you want, but you can wrap your `content` and add a class or id and use it to append events (using jQuery or plain DOM).

**Comment by knapeto** [comment]
Nice tip ! I will try it and give you feedback.

**Comment by hpneo** [comment]
I just saw there's a `click` callback in `drawOverlay`, I've updated your fiddle: https://jsfiddle.net/qdcmrnta/1/
