### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by hughsaffar** [hpneo/gmaps#438]
I am just wondering is there a way I can implement Google Maps Heatmap functionality with this plugin?

**Comment by hpneo** [comment]
Yes, you can use it like this: https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap, and change this line:

`heatmap.setMap(map);`

with:

`heatmap.setMap(map.map);`

When `map` is a `GMaps` instance.

**Comment by hughsaffar** [comment]
Awesome! :+1:
