### ISSUE TITLE
Better solution removeOverlay

### ISSUE THREAD

**Issue by knapeto** [hpneo/gmaps#440]
Hi,

I find function called removeOverlay. I think it would be better to delete by position (lat, lng). Can you rewrite it ?

Thanks.

**Comment by hpneo** [comment]
You can save the position (options.lat and options.lng) in the `overlay` object and then filter the `map.overlays` property to find the overlay that matches the requested position, and use `removeOverlay` to remove it. I'm always open to contributions, as long as you don't break backwards compatibility.
