### ISSUE TITLE
Use with https?

### ISSUE THREAD

**Issue by BenjaminDowns** [hpneo/gmaps#442]
I've been having issues with getting Gmaps to work with https. The error I keep getting is: 

"Mixed Content: The page at 'https://mysite/foo/bar' was loaded over HTTPS, but requested an insecure script 'http://maps.google.com/maps/api/js?sensor=true'. This request has been blocked; the content must be served over HTTPS."

I imagine this is a known issue, but I couldn't find any mention of it in the documentation. Is there a workaround?

**Comment by jeffconklin** [comment]
Anytime you are requesting a secure URL (https), loading non-https content
will pretty much eliminate the "security"/privacy that you are looking for.
Meaning, when you load https://...anything, all the URLs within your page
need to also be using the https protocol or modern browsers will just block
the 'bad"/insecure content, like you are seeing.

To address this, you can swap out http://maps.google.... for
https://maps.google.com/maps/api/js?sensor=true

You may want to check out this information within their docs...

https://developers.google.com/maps/documentation/javascript/tutorial#https-or-http

Hope this helps.


Jeff Conklin
jeffconk@gmail.com
(609) 439-3038
http://jeffconklin.com
