### ISSUE TITLE
Unable to include GMaps in my application

### ISSUE THREAD

**Issue by akshayjha28** [hpneo/gmaps#443]
Hi

I am unable to include Gmaps in my application.

Application is based on backbone and marionette and I use require JS to define all plugins and their dependencies in main.JS

I have tried the below method

1. Including Gmaps in my code base and defined the path in main.JS
2. I have replaced googlemaps! in gmaps define  to 'async!'async!https://maps.google.com/maps/api/js?sensor=true&'
3. called gmaps in the file where it is required

It is giving the following errors

1. Uncaught ReferenceError: GMaps is not defined

2. net::ERR_NAME_NOT_RESOLVED - While fetching 
http://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3A%2F%2Flocalhost%3A9000%2F&callback=_xdc_._wvqiwx&token=126068

Please can anyone help?

**Comment by ripienaar** [comment]
```net::ERR_NAME_NOT_RESOLVED``` means the dns did not resolve the name, from what you're saying I guess its failing to resolve ```maps.googleapis.com```, check if your computer can resolve that name?

**Comment by akshayjha28** [comment]
Hi

The above issue is resolved now.

The main problem is with the GMaps getting undefined.

I am not able to access the method

**Comment by hpneo** [comment]
GMaps is exposed as global variable (`window.GMaps`), but I don't have a demo using RequireJS so I don't know if the file `gmaps.js` works fine. If you provide me one I can debug it.
