### ISSUE TITLE
Using Javascript trick to prevent FOUC breaks gMaps

### ISSUE THREAD

**Issue by krishunt** [hpneo/gmaps#444]
I use gMaps.js on my Joomla site extensively. I was having an unrelated issue with my site where the entire navigation menu would flash with unstyled content when each page would initially load, so I implemented <a href="http://goo.gl/PVsR7">Brad Baxter's method</a> of hiding all content with Javascript and then enabling it again at at the end of the page with a little more Javascript. This worked to prevent the FOUC, but it also removed all my gMaps, and I don't know why. I tried reordering things, like re-enabling the page content immediately after the navigation menu loads, but before the maps should load, but it didn't help.

**Comment by hpneo** [comment]
I can't help you without see a demo of the bug. Has your map been created without throwing errors? Do your map's div contain other divs (check the screenshot)? Did the map's div have width and height?
![screenshot1](https://cloud.githubusercontent.com/assets/611699/9726011/686b22f2-55b2-11e5-8c0c-893b9c1b69e0.png)
