### ISSUE TITLE
Avoid unhandled script error if API unavailable.

### ISSUE THREAD

**Issue by pope1ni** [hpneo/gmaps#446]
I have a problem where some customers are unable to access the Google Maps API due to filtering restrictions. In this situation my entire page stops loading because `gmaps.js` throws an unhandled script error in the absence of `window.google.maps`.

Would it be possible to change the `throw` to `console.error()` (obviously with a check for `window.console` first) and then return `undefined` from the factory? This way it is possible to check for the failed loading of `GMaps` and just disable the mapping component on my page without affecting the rest of the experience.

**Comment by pope1ni** [comment]
Also, the message currently refers to the old location for the API.

Google's documentation now specifies `https://maps.googleapis.com/maps/api/js`

**Comment by hpneo** [comment]
Fixed in the 0.4.20 version

**Comment by pope1ni** [comment]
Thanks for the fix.
