### ISSUE TITLE
Gmaps only works on browser resize

### ISSUE THREAD

**Issue by coastalpro** [hpneo/gmaps#448]
My gmaps only shows a grey box, unless I resize my window.

I found that if I do Inspect Element, the map shows fine (minus going to the center).

How can I fix this, and how can I have it centered on resize?

Here's a link to my gmaps. Look in the Location Tab.

http://www.myrtlebeachcondos.net/booking/property.php?PropertyId=673&CheckIn=10/8/2015&CheckOut=10/13/2015&ResortName=Crescent%20Keyes&Bedrooms=2

**Comment by jeffconklin** [comment]
It looks like you are loading the map on the second tab on your page. Since
this is hidden when the page loads, the map element does not have a height
or width (because it is not "there"). So the map is loaded, and google has
returned the tiles back to the no height/width map... which makes it look
empty. Though I don't have a specific solution, you can most likely find
the answer is you search for "Loading google maps on a hidden div". I
believe the fix here might be to initialize or "pretend" that the browser
has resized when the map finally becomes visible. You can either initiate
the map when someone actually clicks the location tab, or perform a resize
call on google maps specifically after the tab is displayed.


Jeff Conklin
jeffconk@gmail.com
(609) 439-3038
http://jeffconklin.com

**Comment by oharkins** [comment]
Looks like someone has had this issue as well here is an Idea. 

http://stackoverflow.com/questions/4064275/how-to-deal-with-google-map-inside-of-a-hidden-div-updated-picture <http://stackoverflow.com/questions/4064275/how-to-deal-with-google-map-inside-of-a-hidden-div-updated-picture>

**Comment by lenamtl** [comment]
Hi,

I'm having the same issue today, I don't know why, because it was ok before.
The website is base on skeleton responsive framework...

I have tried some of stackoverflow solution with no luck.

**Comment by ejlocop** [comment]
try refresh() function

**Comment by rawsonkara** [comment]
sounds like you are trying to render the area before the element is show in your dom. make a simple statemachine to check for the element to be defined, then call refresh();

**Comment by ahmdrami** [comment]
If you are still looking for a solution then load inside setTimeout with 500 delay at least.

**Comment by satriani04** [comment]
same problem here..  
maps only show grey background, but when i open inspect element it show up.
solution please

thank you

**Comment by sivabudh** [comment]
It's not just opening inspect element, if you resized the browser, Google Maps would render.

**Comment by chriscz** [comment]
I've tried many of the solutions online, but got none of them to work, the gray block kept reappearing. I found that `opacity:0` worked well, however the element would still take up space on the page which is exactly what I was trying to avoid. I also tried `width:0; height:0` but some  elements in the hidden block did not inherit from their parent. 

#### Stylesheet
```css
/* moves the element out of sight*/
.hiddenmap {
    opacity: 0;
    position: absolute;
    bottom: 0
}

/* ensures that the content fills its parent when shown again */
#map-content {
    height: 100% !important;
    width: 100% !important;
}
```
Note that the `hidden-map` class will not work as expected if the map is contained within an relative parent element. i.e. the parent has `position: relative`. Look at http://learnlayout.com/position.html for more information regarding element positioning.


#### HTML
```html
<div class="hiddenmap">
    <div style="width:100%; height:200px; overflow:hidden">
        <div id="map-content"></div>
    </div>
</div>
```

When display was necessary, I removed the property and refreshed the map. You may need to defer this operation by using `setTimeout` with a very small time.

In Gmaps:
```javascript
map.refresh();
```

Or when using google maps directly
```javascript
google.maps.event.trigger(map, 'resize');
```

#### Versions
- `gmaps == v0.4.22`
- `google.maps.version == "3.27.8"`

#### Some material I looked at 
- http://stackoverflow.com/questions/15855826/css-alternatives-to-style-displaynone
- http://blog.codebusters.pl/en/google-maps-in-hidden-div/
- https://productforums.google.com/forum/#!topic/maps/7tV5PZiD_gA

**Comment by sivabudh** [comment]
I got it to work. Here's the code that worked for me. I hope it helps somebody out there. It uses Haml, but I'm sure any programmers can figure it out.

```
%script{src: "https://maps.googleapis.com/maps/api/js?key=<Your API key>", type: "text/javascript"}

:javascript
  function showGoogleMaps() {

    // Put your code here

    // I made `map` a Javascript global variable
    map = new google.maps.Map(...);

    // Same as my marker (if you needed it
    marker = new google.maps.Marker({ ... });

    marker.setMap(map);
  }

  // and here's the key that got it to work!
  google.maps.event.addDomListener(window, 'load', showGoogleMaps)
```

**Comment by sivabudh** [comment]
Seems like someone also came across the same solution:

http://stackoverflow.com/a/29572745/65313
