### ISSUE TITLE
[help] about checkGeofence method ?

### ISSUE THREAD

**Issue by striderblue** [hpneo/gmaps#451]
I have a problem with checkGeofence.
In my understand if lat,lng are inside the area , checkGeofence should return = 'true' and lat,lng are outside the area , checkGeofence should return = 'false' right?

But I get all 'true' . 
Here my code:
var circle = map.drawCircle({
        lat: 14.0772563,
        lng: 100.6123066,
        radius: 350,
        strokeColor: '#432070',
        strokeOpacity: 1,
        strokeWeight: 3,
        fillColor: '#432070',
        fillOpacity: 0.6
});
var x = 14.0772563;
var y = 100.6123066;
var x1 = 14.0723582;
var y1 = 100.6063637;

var a = map.checkGeofence(x,y,circle);
console.log('a = ' + a);
var b = map.checkGeofence(x1,y1,circle);
## console.log('b = ' + b);

a = true
## b = true    <---- this should be 'false'

Please, I need some advice.
Thank you.

**Comment by sillassoares** [comment]
Check if you have the geometry library

ex: https://maps.googleapis.com/maps/api/js?libraries=geometry

**Comment by hpneo** [comment]
Please put your code in jsfiddle or CodePen, but it might be what @sillassoares says.
