### ISSUE TITLE
Bindind a circle to marker

### ISSUE THREAD

**Issue by pithhelmet8669** [hpneo/gmaps#453]
Created a series of markers that follow the vehicles.   Added a circle around the marker and bound it to the marker.

Need to remove the marker and the associated / bound circle.

removeMarker removes the marker, but the circle that was bound to it does not get erased.

Here is the code that kicks off the marker creation and circles
                GetOpenServiceOrders();
                GetLatestVehicleStatus2();

                var VehicleTicketMovementTimer = setInterval(function () {
                  var x = current_map.markers.length;
                  for (var i = 0; i < x; i++) {
                     current_map.removeMarker(i);
                  }
                  GetOpenServiceOrders();
                  GetLatestVehicleStatus2();
                }, 10000);

function GetLatestVehicleStatus2OnComplete(result) {
  var status_text = "";
  var records = result.split("*");
  var len = records.length - 1; 

  for (var i = 0; i < len; ++i) {
    var record = records[i].split("|");
    var lll = new google.maps.LatLng(record[4], record[5]);
    var m = current_map.addMarker({
      lat: record[4],
      lng: record[5],
      title: "Vehicle :" + record[2],
      labelStyle: { opacity: 0.50 },
      icon: icon_image,
      infoWindow: {
        content: '<p>HTML Content</p>'
      }
    });
    var c = current_map.drawCircle({
      strokeColor: '#000000',
      strokeOpacity: 0.4,
      strokeWeight: 2,
      fillColor: '#c3fc49',
      fillOpacity: 0.15,
      radius: eval(record[18]) * 2
    });
    c.bindTo('center', m, 'position');
  }
}

**Comment by hpneo** [comment]
To remove a circle you need to call `removePolygon`, passing the circle created with `drawCircle`.

**Comment by amenadiel** [comment]
C.bindTo('map',m);

Should do the trick as well

**Comment by hpneo** [comment]
Cool! I didn't know that. I'm closing this now.
