### ISSUE TITLE
map.SetCenter is causing too much recursion error

### ISSUE THREAD

**Issue by ejlocop** [hpneo/gmaps#455]
Hi,

``` javascript
map.setCenter(150,150);
map.setCenter({ lat: 150, lng: 150}); 
```

is causing an error. i can't seem to find whats causing this error. can someone please help me?
here is my map creation.

``` javascript
mapa.map = new GMaps({
                el: '#map',
                width:'100%',
                height:'300px',
                lat: 13.0000,
                lng: 122.0000,
                zoomControl : true,
                zoomControlOpt: {
                    style : 'SMALL',
                    position: 'TOP_LEFT'
                },
                panControl : false,
                streetViewControl : false,
                mapTypeControl: false,
                overviewMapControl: false,
                // zoom_changed: function() {
                //     console.log('zooom!');
                //     if (mapa.circle != null) {
                //         var curRadius = mapa.circle.getRadius();
                //         var curZoom = mapa.map.getZoom();
                //         var p = mapa.getScale(mapa.lat, curZoom);
                //         console.log(curRadius);
                //         // mapa.curRadius = p;
                //         // mapa.circle.setRadius(p);
                //     }
                // }
            });
```

**Comment by hpneo** [comment]
I've tried in http://hpneo.github.io/gmaps/ with 150, 150, and the map doesn't render any location. It seems to be a *bug* from Google Maps, since I've replicated the bug using Google Maps API:

```js
// mapa.map.map is the reference to the original Google Maps Map object:
mapa.map.map.panTo(new google.maps.LatLng(150, 150));
```

Or check here: http://www.findlatitudeandlongitude.com/?lat=150&lon=150&zoom=7&map_type=G_NORMAL_MAP#.Vk6sR98veRt

**Comment by ejlocop** [comment]
thanks.

what google map url are you using @hpneo  ? 
ive used http://maps.googleapis.com/maps/api/js?v=3.20&sensor=true and it's still working til last day, but when i checked it earlier and tried to setCenter. it's now causing me this error.
is it a google maps bug?

**Comment by hpneo** [comment]
I always use the latest version (without `?v=xxx`). Maybe you need to use an earlier version?

**Comment by emitategh** [comment]
I'm still having the same problem! tried with that version but nothing!

**Comment by hpneo** [comment]
Please post your code in jsfiddle.net, codepen or similars

**Comment by dstream** [comment]
@ejlocop I think because gmap didn't support pass object to setCenter method (line 581), so you shouldn't do this: map.setCenter({ lat: 150, lng: 150}); 
it should be map.setCenter(150, 150)
