### ISSUE TITLE
TravelRoute with a set of coordinates

### ISSUE THREAD

**Issue by elyfran** [hpneo/gmaps#456]
Good afternoon, 

First I want to congratulate the initiative of this project.

I wonder how I can create a travel route (map.travelRoute) without informing origin and destination, only with a set of coordinates.

it would be possible?

**Comment by hpneo** [comment]
I don't know if I understand correctly, but that set of coordinates can be your origin and destination. Also, you can use that coordinates as waypoints (you must use the `waypoints` property in `travelRoute`).
