### ISSUE TITLE
How to remove controls?

### ISSUE THREAD

**Issue by youradds** [hpneo/gmaps#460]
Hi,

In the updated, you say:

0.4.13  Add functionality to remove controls

I can't for the life of me, work out how to do this though. Any guide? 

Thanks

Andy

**Comment by youradds** [comment]
Someone just answered me on SO:

		modal_map = new GMaps({
	        disableDefaultUI: true,
	        div: '#popup_map',
	        lat: coords[0],
	        lng: coords[1]
	    });

**Comment by hpneo** [comment]
Hi, it's related to remove custom controls:  https://github.com/hpneo/gmaps/blob/0.4.13/lib/gmaps.controls.js#L53 (like this: http://hpneo.github.io/gmaps/examples/custom_controls.html)
