### ISSUE TITLE
Open modal clicking on marker

### ISSUE THREAD

**Issue by ccataldov** [hpneo/gmaps#461]
Dear.
I need this: 
google.maps.event.addListener(marker, 'click', function() 
   {
        $('#myModal').modal('show')
    });
 in gmaps.
Example Bootply: http://www.bootply.com/ccataldo/NfMP3BcdY1
Thank you.

**Comment by hpneo** [comment]
You can use `GMaps.on`:

```js
GMaps.on('click', marker, function() {
  $('#myModal').modal('show');
});
```
