### ISSUE TITLE
display a map

### ISSUE THREAD

**Issue by xavierartot** [hpneo/gmaps#464]
Hi,
my map doesn't display, and I don't have any error js?
Thank you
## edit

```
      map = new GMaps({
        el: '#map',
        lat: -12.043333,
        lng: -77.028333,
        zoomControl : true,
        zoomControlOpt: {
            style : 'SMALL',
            position: 'TOP_LEFT'
        },
        panControl : false,
        streetViewControl : false,
        mapTypeControl: false,
        overviewMapControl: false
      });
```

```
        <div class='map' id='map'>
          <img src='http://placehold.it/769x250' class='img-responsive' alt='poster mobile' />
        </div>
```

**Comment by jrdr270987** [comment]
map = new GMaps({
	div: '#map',
	lat: -12.043333,
	lng: -77.028333,
	zoom: 13
});
 i have this way for my map. you must change "el: '#map'," for "div: '#map'," change this and check. sorry for my english. i am from venezuela.

**Comment by hpneo** [comment]
It should work with `el` or `div`, and `#map` must have a width and height. Please post a demo with your code (you can use jsfiddle.net).

**Comment by xavierartot** [comment]
Thanks, I just copy the css in the example.`
