### ISSUE TITLE
setIcon not always refresh icon

### ISSUE THREAD

**Issue by fleduc** [hpneo/gmaps#468]
I've created a jQuery Mobile app using gmaps.js and found some strange random behavior with setIcon function.

First I load markers from DB and create markers as found in "Working with JSON" example

Don't worry, everything is working fine...

When I click on collapsible-set I'm going to the marker on the map, center it and change the icon using "setIcon" function to show what marker is selected.

Again, everything is working fine...

The problem I have found is, when I click on each of the collapsible, once at the time, when arriving on number 6 and 14, the icon doesn't change?  If I click a few times ont number 6, it will finally changes. continuing and coming back to these numbers, still doesn't change the icon...

I also found that these numbers are not fixed, sometimes it is num 4 and 17 or 11??? 

Is there a way to force gmap to refresh the icon or the map to resolve this annoying problem? 

App can be found on http://axsyst.com/webdemo/testgmaps/test_index.php

**Comment by hpneo** [comment]
I checked the app and saw this in the Marker 14:

![captura de pantalla 2016-01-09 a las 15 20 52](https://cloud.githubusercontent.com/assets/611699/12218147/9aa49bca-b6e4-11e5-855c-2f14dbe7db27.png)

Apparently there are few markers overlapping others. I this case, the marker #14 and marker #22 (I also checked in the markers #6 and #20, occurring the same).

**Comment by fleduc** [comment]
Wow! this mean that there is many companies located in the same address, the same building!
I didn't tough about this one...

Thanks

Is there a way to have a marker put in front of all others or should I redraw it?

**Comment by hpneo** [comment]
You can change the zIndex property.

**Comment by fleduc** [comment]
Would you have the exact command to change the z-index, I'm trying to get a hold on this marker with jquery but it doesn't work?

Thanks again

**Comment by hpneo** [comment]
Use `marker.setZIndex(number)`. Is a different z-index from CSS, but the logic is the same.
