### ISSUE TITLE
Documentation incomplete for geocode, geolocate etc..

### ISSUE THREAD

**Issue by gkimpson** [hpneo/gmaps#469]
Not so much a technical issue but having reviewed the docs I cannot see any detailed documentation on the following -

GMaps.geocode
GMaps.geolocate
GMaps.Route
GMaps.staticMapURL

Can you estimate if this will this be added at any point in the future? (Apologies if this isn't the best place to leave this comment).

P.S Great library by the way!

**Comment by hpneo** [comment]
Hi, thanks for your words! Maybe this weekend I will take a look to the documentation.
