### ISSUE TITLE
Using gmaps within a jQuery UI Accordion/Tabs doesn't appear to work

### ISSUE THREAD

**Issue by gkimpson** [hpneo/gmaps#472]
I am trying to load my Google Map within a jQuery UI Accordion - the accordion works but the map doesn't display (even though it has loaded in the DOM ok) - Any thoughts on how to load within the jQuery Accordion

       $(document).ready(function(){
      // initialise gmaps with default data
      map = new GMaps({
          div: '#gmapsjsMmap',
          lat: 52.4801,
          lng: -1.8835,
          zoom: 7,
          tilesloaded: function() {
              map.refresh();
          }
      });    

    $("#registration_form_area").accordion({
        collapsible: true,
        active: false,
        animate: false,
        beforeActivate: function(event, ui)
        {
            map.refresh();
        }
    });

**Comment by hpneo** [comment]
Have you tried with `activate`? The map needs to know the exact dimensions of its container before using `refresh()`.

**Comment by olegmedvedev** [comment]
For me the following solution works:

`    <style>
        #gmap {
            height: 100%!important;
        }
    </style>

    <script>

        $(document).ready(function() {
            // initialise gmaps with default data
            map = new GMaps({
                div: '#gmap',
                lat: 52.4801,
                lng: -1.8835,
                zoom: 7,
                tilesloaded: function () {
                    map.refresh();
                }
            });

            $("#accordion").accordion({
                collapsible: true,
                autoHeight: false,
                active: false,
                animate: false,
                activate: function (event, ui) {
                    map.refresh();
                }
            });
        });

    </script>`

**Comment by hpneo** [comment]
@olegmedvedev yes, that's exactly what I meant. `map.refresh` should be called after the accordion is activated, no before. Thanks!
