### ISSUE TITLE
markersRemove issue

### ISSUE THREAD

**Issue by miha114** [hpneo/gmaps#473]
I am using gmaps in an application that renders some 2,400 markers on document ready. Needless to say I started looking at markerClusterer. 
Problems started when i tried to update the map with a subset of markers. 
I use an input text field in which the user can type. The value of the field is passed to a Regular Expression as a pattern to be tested against title attribute of the markers array. Matching markers are pushed to a subset array. Then I perform removeMarkers(), followed by addMarkers(subset). This caused my site to freeze. Removing the clusterer clause from my initial on document ready map definition resulted in performance I wanted. 
I have to this is the first site I am constructing and I realise there could be a better and more obvious way of achieving same results. If so I would welcome any advice. Nevertheless when looking at gmaps code for removeMarkers prototype I noticed, that on line 791 (if this.markerClusterer is true) it calls the removeMarker() function (beginns on line 764). This last function also check for markerClusterer and calls itself (line 771). 
I must admit I do not understand wether this recursion should serve some purpose of is it a bug. My guess was (after trial and error and googling) it should be avoided. I commented out the call to removeMarker() inside the removeMarkers() function and added this.markerClusterer.clearMarkers() clause. 
This turned performance from frozen to snappy :-D. 
If my issues result from my unexperience and this post proves to be unhelpful, I apologize. 

Here is my edited vesion of the code, lines 764 through 826:

```
GMaps.prototype.removeMarker = function(marker) {
  for (var i = 0; i < this.markers.length; i++) {
    if (this.markers[i] === marker) {
      this.markers[i].setMap(null);
      this.markers.splice(i, 1);

      if(this.markerClusterer) {
        this.markerClusterer.removeMarker(marker);
      }

      GMaps.fire('marker_removed', marker, this);

      break;
    }
  }

  return marker;
};

GMaps.prototype.removeMarkers = function (collection) {
  var new_markers = [];

  if (typeof collection == 'undefined') {
    for (var i = 0; i < this.markers.length; i++) {
      var marker = this.markers[i];
      marker.setMap(null);

      if(this.markerClusterer) {
      	//this.markerClusterer.removeMarker(marker);
        this.markerClusterer.clearMarkers(); // My addition.
      }

      GMaps.fire('marker_removed', marker, this);
    }
    
    this.markers = new_markers;
  }
  else {
    for (var i = 0; i < collection.length; i++) {
      var index = this.markers.indexOf(collection[i]);

      if (index > -1) {
        var marker = this.markers[index];
        marker.setMap(null);

        if(this.markerClusterer) {
          this.markerClusterer.removeMarker(marker);
        }

        GMaps.fire('marker_removed', marker, this);
      }
    }

    for (var i = 0; i < this.markers.length; i++) {
      var marker = this.markers[i];
      if (marker.getMap() != null) {
        new_markers.push(marker);
      }
    }

    this.markers = new_markers;
  }
};
```
Sorry for the long post, 
Miha.

**Comment by hpneo** [comment]
Hi, sorry for the long delay. I'm intrigued with this bug, because the `removeMarker` function you commented isn't from gmaps but from the cluster, so it doesn't perform recursive calls. **But** clearly was a bad choice to call `markerClusterer.removeMarker` every time a marker is removed. I will change the `markerClusterer.removeMarker` to `markerClusterer.clearMarkers` and put it outside the for loop.

Thanks for your help!
