### ISSUE TITLE
while using inside call back i found this error 

### ISSUE THREAD

**Issue by imadarif** [hpneo/gmaps#474]
Uncaught TypeError: fence.containsLatLng is not a function

**Comment by hpneo** [comment]
It depends what kind of geofence do you have. It works when `fence` is an instance of `google.maps.Polygon` or `google.maps.Circle`. It doesn't work with `google.maps.Rectangle` but you can use this polyfill:

```javascript
google.maps.Rectangle.prototype.containsLatLng = function(latLng) {
  return this.getBounds().contains(latLng);
};
```

**Comment by imadarif** [comment]
thanks man (Y) issue resolved
