### ISSUE TITLE
Custom Infowindow styling

### ISSUE THREAD

**Issue by ArchimidisM** [hpneo/gmaps#476]
Dear all I am trying to style the info window , and I follow some tutorials however it seems that it cannot be fully customized.

Is there any tutorial available for customizing the infowindow?

**Comment by miha114** [comment]
Hi there. What exactly are you trying to do? 
One way to go would be to give your infoWindow a class like this:
```
map.addMarker({
  lat: -12.043333,
  lng: -77.028333,
  title: 'Lima',
  infoWindow: {
    <div class="myClass">Lorem ipsum</div>
  }
});
```
Then you write some CSS code to go with it. 
The other option is to look into [documentation](https://hpneo.github.io/gmaps/documentation.html#GMaps-createMarker) where it says:
infoWindow 	object 	Object with all options defined in [google.maps.InfoWindowOptions](https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions).

Hope this helps.

**Comment by hpneo** [comment]
If you want a full customization you must use Overlays (http://hpneo.github.io/gmaps/examples/overlays.html).
