### ISSUE TITLE
Using Browserify to include gmaps.js

### ISSUE THREAD

**Issue by mark-win** [hpneo/gmaps#482]
Use
`window.GMaps = require('gmaps');`
if you get
- Uncaught ReferenceError: GMaps is not defined

when using Browserify to assemble your JS. Seems obvious now, but I leave it here for anyone else, struggling with that for a while like me.
Thx to hpneo for his work and hinting at `windows.GMaps` in #443

**Comment by hpneo** [comment]
Thanks! I added your tip in the [wiki](https://github.com/hpneo/gmaps/wiki/Tips)
