### ISSUE TITLE
Street View

### ISSUE THREAD

**Issue by vegas2033** [hpneo/gmaps#483]
I'm using your library in one of my application and just noticed that the street view does not work. I also tested with the example you provided on your website and the same issue occurs (so it's not my code).

When I attempt to do a street view, a partial street view comes up. Most of it is grey but some pieces triangular pieces appear to be working (Cf. attached image)
![gmaps](https://cloud.githubusercontent.com/assets/18350240/14385991/fdfe66e2-fd70-11e5-90c3-7f5dc72277a4.jpg)

Is this a known issue? is there a fix for it? 

Thanks in advance

**Comment by vegas2033** [comment]
After further testing, this appears to be an issue only with Google Chrome

**Comment by hpneo** [comment]
Not sure, but it can be a bug in the site's css.
