### ISSUE TITLE
No A B markers in route

### ISSUE THREAD

**Issue by conor909** [hpneo/gmaps#484]
I'm using the following code to display a route, which works nicely, but there are no A B markers displayed.  I can create markers at these positions manually, but then I have to remove them manually too, which is verbose if there is a way of getting them to display along with the route, which I can see from Google Map Javascript API examples.
    
`````
map.drawRoute({
      origin: [myOriginLat, myOriginLng],
      destination: [myDestinationLat, myDestinationLng],
      travelMode: "driving",
      strokeColor: '#3b78e7',
      strokeOpacity: 0.6,
      strokeWeight: 6
});
`````

**Comment by hpneo** [comment]
You can use [`renderRoute`](https://github.com/hpneo/gmaps/blob/master/lib/gmaps.routes.js#L115):

```javascript
map.renderRoute({
  origin: [myOriginLat, myOriginLng],
  destination: [myDestinationLat, myDestinationLng],
}, {}); // empty object is DirectionsRenderer's options.
```

It uses the same options as getRoutes

**Comment by conor909** [comment]
Ah ok thanks.  Its difficult to navigate the docs but it's a fantastic library

**Comment by hpneo** [comment]
Thanks, I'm working in a new documentation section, hopefully I'll finish this month.
