### ISSUE TITLE
external link show infowindow

### ISSUE THREAD

**Issue by stillers80uk** [hpneo/gmaps#485]
I've been working through the JSON example and I would like to show the infowindow when someone clicks on the .pan-to-marker link. The infowindow shows when one clicks on the map marker itself but I would like it to show when the .pan-to-marker link is clicked.

What can I try to get this to work?

**Comment by hpneo** [comment]
Hi, sorry for the late reply. You can add an infowindow to each marker (or use a single infowindow and change its content if the infowindow will be shown once in the map at the same time). And use this code:

```javascript
var map = new GMaps(/*...*/);

var marker = map.addMarker(/*...*/);

marker.infoWindow.open(map.map, marker);
```
