### ISSUE TITLE
Geocoding Gets the wrong location

### ISSUE THREAD

**Issue by jkkenzie** [hpneo/gmaps#486]
Hi, when i try to get a location on the example http://hpneo.github.io/gmaps/examples/geocoding.html, it gives me the wrong location all the time. As well as other examples like http://gmaps-samples.googlecode.com/svn/trunk/geocoder/singlegeocode.html and that http://rjshade.com/projects/gmaps-autocomplete/.  Is there an update using google V3 library.

**Comment by hpneo** [comment]
It's probably a issue with Google Geocoding Service. Nothing I can do from here.
