### ISSUE TITLE
Geolocation failed: Only secure origins are allowed

### ISSUE THREAD

**Issue by SylvainMarty** [hpneo/gmaps#487]
Hi,

I've some troubles with Geolocation. It worked fine before the new Google Chrome update.

Now, the geolocation doesn't work on a non-ssl (non-secure) website.
This is displayed on the browser console :
`getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`
Then : 
`Geolocation failed: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`

Is there a solution for that ?

Thanks in advance !

**Comment by hpneo** [comment]
I think is a browser *issue*, nothing I can do from this side 😞

**Comment by SylvainMarty** [comment]
Hi !

After the last Chrome update, the methods `getCurrentPosition()` and `watchPosition()` aren't more allowed from a non-ssl adress.

There is only two way to solve that :
- Install a ssl certificate
- Switch to an other Map API

This two methods come from to the browers, not from the Google Maps API.

Thanks for your answer !
