### ISSUE TITLE
GMAP CLUSTER don't worked

### ISSUE THREAD

**Issue by Archangel236** [hpneo/gmaps#488]
Hey. Link to https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/ has stopped working. Not  displayed on the map icons. How can go out with a situation.

**Comment by hpneo** [comment]
Google moved their code to GitHub: https://github.com/googlemaps/js-marker-clusterer.
I'll update the site with the new link, thanks!
