### ISSUE TITLE
switch array lat and long

### ISSUE THREAD

**Issue by kazhuyo** [hpneo/gmaps#491]
i've try to convert kmz file into json file and get the marker point
but, the position between lat and long is inverted different from json.

eg : 
      path = [
      [136.8821606600132,-3.733148847727767],
      [136.8821558955888,-3.732922580537378],
      [136.8816842881533,-3.732622429203599]
     ]

how to switch between lat and long? so the script read
136.8821606600132 = as long
and 
-3.733148847727767 = as lat

**Comment by conor909** [comment]
I think this is an issue with your data and not gmaps. As far as I can see you need to look into implementing  a "flat map" JavaScript function. It helps you when your data object is an array of arrays.

**Comment by hpneo** [comment]
If it's a polygon you try to draw, use the `useGeoJSON` property. GMaps doesn't support geoJSON formatting (which is [longitude, latitude] instead [latitude, longitude]) right now.
