### ISSUE TITLE
Ask gmaps.js Maker Label

### ISSUE THREAD

**Issue by jeok70** [hpneo/gmaps#492]
that gmaps.js label can change the Url?

https://jsbin.com/mejipovada/1/edit?html,js,output

View Label under the Maker

My Source code is 
`@model IEnumerable<WebApplication1.Models.SchoolAddress>

@section scripts{

    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="@Url.Content("~/Scripts/gmaps.js")"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            map = new GMaps({
                div: '#map',
                lat: 0,
                lng: 0,
                zoom:15
            });

   @foreach (var item in Model)
   {

       <text>
            var i =  '@item.經緯度';
            i = i.split(',');

            map.setCenter(24.981388, 121.508526);
            map.addMarker({
               lat: i[0],
               lng: i[1],
               label: "A",
               Anchor: new google.maps.Point(3, 30),
               labelClass: "labels", // the CSS class for the label

       });

       </text>
       }
   });

    </script>
    <script>

    </script>
}

<div id="map"></div>

<style>
    #map {
        display: block;
        width: 98%;
        height: 500px;
        margin: 0 auto;
    }
</style>
<style type="text/css">
    .labels {
        background-color: rgba(0, 0, 0, 0.5);
        border-radius: 4px;
        color: white;
        padding: 4px;
    }
</style>`

**Comment by hpneo** [comment]
Not really. You must create your own labels with [drawOverlay](http://hpneo.github.io/gmaps/examples/overlays.html).

**Comment by vasilp** [comment]
Actually with the Google Maps API you can create very easily marker with custom label (useful for vector icon) - https://developers.google.com/maps/documentation/javascript/reference/3/#MarkerLabel

Also solutions could be found here: https://stackoverflow.com/a/39945227/449405

So it would be good to have the option to utilize the LabelMarker class with this plugin also...
