### ISSUE TITLE
Change Marker Color

### ISSUE THREAD

**Issue by Kaimite** [hpneo/gmaps#493]
Hello, 
Can you show me how to change marker color or use au custom marker ? 
Thank's for your work ! 

Kaimite

**Comment by conor909** [comment]
You just put a link to your marker image as the icon property. 

'''''
addMarker({
     position: yourLatLng,
     map: yourMap,
     icon: "path/to/image.png"
});
'''''

**Comment by Kaimite** [comment]
Thank's :)
