### ISSUE TITLE
Ask gmaps.js Place ID

### ISSUE THREAD

**Issue by jeok70** [hpneo/gmaps#498]
Could you do me a favor,please. I'd like to ask you somthing about google map api problem.  Its about how to use PlaceID Finder in gmaps.js. If you see this message please contact me, thanks.

**Comment by hpneo** [comment]
Hi, I think you're asking about geocoding? Check [this example](https://github.com/hpneo/gmaps/blob/master/examples/geocoding.html) and just change `address` for any of the parameters [passed here](https://developers.google.com/maps/documentation/javascript/reference#GeocoderRequest)
