### ISSUE TITLE
Using setZoom() api changes the center of the map.

### ISSUE THREAD

**Issue by nkolban** [hpneo/gmaps#499]
I have a gmap that is centered on a specific location.  In my browser I can zoom in and zoom out using the map controls.  However, if I try and change the initial zoom level by calling "setZoom()" on my gmap or by setting an initial "zoom: <value>" configuration value, the map is no longer centered where I expect it to be.  The centering appear to drift as a function of the zoom level.  If I set an initial zoom value of 15, it is centered correctly.  If I set a zoom value of 14, the centered is a little south/east of where it should be.  This repeats.  If I am initially centered in Dallas Texas and set a zoom of 5,  the drift centers my map VERY south east (near Cuba and Puerto rico).

**Comment by hpneo** [comment]
Could you provide me a demo to debug? I tried in the [homepage's map](http://hpneo.github.io/gmaps/) and didn't see any change. `setZoom` calls the native `setZoom` method from the `google.maps.Map` instance.
