### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by x5tuts** [hpneo/gmaps#508]
Hi for some unknown reason the map does not seem to be working at all please see demo here http://x5tuts.altervista.org/addons/maps/ apparently it says I need an API KEY any help would be appreciated.

thanks

**Comment by Masatoshi** [comment]
You should set Referer on Google Developer Console.

**Comment by wetink-peter** [comment]
I believe I am also experiencing this problem.

Could you be a little more specific with where to do this? Do I have to add an API key to every site that I develop? Do I need to include it in the options or anything?

**Comment by bdthemes** [comment]
Same issue me too!

**Comment by Masatoshi** [comment]
API KEY is required every sites.

`
<script src="https://maps.google.com/maps/api/js?key={{YOUR_API-KEY}}"></script>
`

One unique API KEY can be used on sites, but you have to add URLs as Referer on Google Developer Console.
I think acquiring API KEYs is another topic. So you'd better to google how to get API KEY and use it.
