### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by SndrL** [hpneo/gmaps#510]
Hi,

I am using gmapjs to display a simple map.
my code is basic and it **works on my localhost**. Even if I open my .html file, the map **works**.
Only when I upload it to my webhost it stops working. (I even tried another provider)

I get this console error:
`Uncaught TypeError: Cannot read property 'prototype' of undefined`
in common.js:48

I've been searching through other issues but I can't seem to get this to work.
What am I doing wrong?

For reference, my code:
`var map = new GMaps({
    el: '#map-canvas',
    lat: 51.000000,
    lng: 4.702637,
    zoom: customZoomLevel,
    zoomControl : true,
    zoomControlOpt: {
      style : 'SMALL',
      position: 'TOP_LEFT'
    },
    scrollwheel: false,
    panControl : false,
    mapTypeControl: false,
    streetViewControl: true,
    overviewMapControl: false,
    scaleControl:true,
    fullscreenControl: true,
  });`

**Comment by evgeniy-arapov** [comment]
+1

**Comment by tankerkiller125** [comment]
I've also had this problem. Mine however is also inside an AngularJS project (though it shouldn't matter). My problem doesn't exist on a local webserver but the second I put it on a production site I get this error.  I originally thought it was an API key problem but adding the API key actually made it worse by causing the localhost to also error. I'm hoping theirs a fix for this soon.

**Comment by pixelcave** [comment]
Hey guys, I had the same problem but it turned out to be an API key issue. All urls which were using Google Maps will still work for now but all the new urls will have to use an API key. It is not enough to create an API key though, you will also have to enable Google Maps to be used with the key you've created from the overview page at https://console.developers.google.com Hope that helps a bit ;-)

**Comment by tankerkiller125** [comment]
@pixelcave Thanks. It also appears that if you want to use Geoposition you'll need to enable that API as well otherwise it will also error out.

**Comment by SndrL** [comment]
Thanks for the info guys!

So this means you need an API key for every domain using gmaps. 
Why has this suddenly changed?

**Comment by tankerkiller125** [comment]
@SndrL more than likely a few bad actors abused the fact that they didn't need an API key which is resulting in the need for the keys now.

**Comment by tankerkiller125** [comment]
Little update to my situation. If you want your credentials to work on both `domain.tld` and `www.domain.tld` you must have both in the credentials. My way of doing this was adding `*.domain.tld/*` and `domain.tld/*` to the allowed domains. This fixed all of my issues.

**Comment by wkerswell** [comment]
Thanks for the update. Was the root of my problems. I would have though `http://www.domain.com/` would have been fine but need the `*` Guess you need to specify the page if you dont use a wildcard
