### ISSUE TITLE
GMaps.staticMapURL incorrect zoom level calculating

### ISSUE THREAD

**Issue by larsomator** [hpneo/gmaps#511]
In lines 104-106 in gmaps.static.js is a check for zoom level set:

``` javascript
if (!options.zoom && options.zoom !== false) {
    options.zoom = 15;
  }
```

The behaviour shall be:
1. if `options.zoom` is not set: use default
2. if `options.zoom` is set and has the value `false`: use default
3. else: use `options.zoom`

The code should change to: 

``` javascript
if (!options.zoom || options.zoom === false) {
    options.zoom = 15;
  }
```

**Comment by hpneo** [comment]
Thank you so much for your contribution and really sorry for the late reply. Since I refactoring the library, I'll add this directly in the new version.
