### ISSUE TITLE
Gmap on my website not show

### ISSUE THREAD

**Issue by thanhansoft** [hpneo/gmaps#513]
Hi all,
My website is http://vantaixuanphuson.com using Gmaps at footer.

I show console debug:
common.js:48 Uncaught TypeError: Cannot read property 'prototype' of undefined
http://maps.google.com/maps-api-v3/api/js/25/8/common.js

But localhost normal operation
Please help me

**Comment by JaxomUK** [comment]
I am having the same issue. As of june 22nd you need an API key from Google, available for free in the google console API Manager. However I have no idea where exactly to put the new script.
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
Hoping for an update by the author

**Comment by TheJester12** [comment]
I am having this issue as well. I've tried it on two projects now and getting the same results. As soon as I add a key I get this error:

**Uncaught TypeError: Cannot read property 'prototype' of undefined**

I love this little library, could somebody help? Otherwise I'll have to revert a few older projects to default Google Maps JS, which I'm not looking forward to! =)

**Comment by wkerswell** [comment]
I am also getting this error now. I too have got a key from google but am still getting an error. 

`
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=MY_KEY">
</script>`

**Comment by JaxomUK** [comment]
This line needs to be placed after your Google Maps JS Scripts
"<script src="https://maps.googleapis.com/maps/api/js?key=YOUR-API-KEY&callback=initMap" async defer></script>"

IE If this is your google geo location script: "<script>
        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
		 function initMap() {
        		var map = new google.maps.Map(document.getElementById('map'), {
          		zoom: 8,
            });
            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.');
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
    </script>"
Then insert code below
"<script src="https://maps.googleapis.com/maps/api/js?key=YOUR-API-KEY&callback=initMap" async defer></script>"
Also it must be included on all templates that use Google maps

**Comment by oneidc** [comment]
The problem is your API KEY
