### ISSUE TITLE
Cant add more than 10 custom markers

### ISSUE THREAD

**Issue by easypizi** [hpneo/gmaps#515]
Hi there!

I've tried to add 35 custom markers in gmap.js, but it looks like script limits it by 10. My skills isn't very high but I've founded that "markers [...]" have limit only for 10 meanings. 

Do you know how to solve this problem?

**Comment by veeeev** [comment]
Have you had any luck with this? i'm stuck with 11 addresses being mapped.

i found that popping up an "alert" between each address slows things down enough that all of my addresses can be mapped, but as soon as i remove the pause created by the alert box, i'm back to 11 markers showing.

**Comment by russianNinja** [comment]
Nooooo man. I choose to comeback to stock markers and solve my task on it. 
There is no problem with them.

**Comment by codetrash** [comment]
has anyone resolved this?

**Comment by avinash8526** [comment]
@russianNinja can u share how u added custom marker ?
