### ISSUE TITLE
Marker dragged event

### ISSUE THREAD

**Issue by hamsddxn** [hpneo/gmaps#517]
I want to ge the new position for my marker after drag, is there a function to solve my problem?

**Comment by ocramot** [comment]
https://github.com/hpneo/gmaps/issues/246

        map.addMarker({
            lat: map.getCenter().lat(),
            lng: map.getCenter().lng(),
            draggable: true,
            dragend: function (m, f) {
                console.log(m)
                console.log(this)
            }
        });

**Comment by ReskatoR-FR** [comment]
`   map.addMarker({
        lat: _lat_,
        lng: _lng_,
        title: 'My Title',
	icon: 'https://maps.google.com/mapfiles/ms/icons/green.png',
	animation: google.maps.Animation.DROP,
        draggable: true,
        dragend: function (e) {
            let lat = e.latLng.lat();
            let lng = e.latLng.lng();
            console.log('latitude : '+ lat +' | longitude : '+ lng);
        }
    });`
