### ISSUE TITLE
no way to clear setDirections and renderedDirections

### ISSUE THREAD

**Issue by spezias** [hpneo/gmaps#518]
I'm using gmaps.js in a little project with the renderRoute function with the following code. 

`
map.renderRoute({
origin: [latlng1.lat(), latlng1.lng()],
destination: [latlng2.lat(), latlng2.lng()],
 travelMode: 'driving'
 },
 {
panel: '#directions',
draggable: true
}`

The route was drawing and the panel works well. But when i start a new routesearch the result append to the existing result. I know renderRoute use the google directionservice and the path is not drawn like a polyline. But how can i clear existing direction results? i've checked the following functions, but nothing works:

directionsDisplay.setDirections({routes: []});
GMaps.directionsDisplay.setMap(null);
map.directionsDisplay.setMap(null);
map.renderedDirections.setMap(null); 
etc... 

Can you help me?

**Comment by ReskatoR-FR** [comment]
try this :
myTravel = map.renderRoute({ origin: …});
then, for delete the existing result :
map.cleanRoute(myTravel);

Enjoy ;)
