### ISSUE TITLE
common.js:47 Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by sarvy26** [hpneo/gmaps#525]
I am using latest version of gmaps. I resolved #MissingApiKey issue but still map is not loading. I am getting the following issue:

```
common.js:47 Uncaught TypeError: Cannot read property 'prototype' of undefined
    (anonymous function)    @ common.js:47
    _.Wa                @ js?key=************_*******:34
    a                   @ common.js:47
    Bm                  @ common.js:48
    (anonymous function)    @ common.js:50
    (anonymous function)    @ common.js:201
    c                   @ common.js:44
    (anonymous function)    @ AuthenticationService.Authenticate:1
```

Please someone tell me what I am missing.

**Comment by jarekbb** [comment]
I have the same problem.

**Comment by qkdreyer** [comment]
Activate Google Maps JavaScript API : https://console.developers.google.com/apis/api/maps_backend/overview

**Comment by R3muSGFX** [comment]
@qkdreyer you sir, deserve a cookie.

**Comment by Dsantacruz** [comment]
Exactly, your must activate google Mpas Javascript Api:

https://console.developers.google.com/apis/dashboard/

**Comment by abrhambas01** [comment]
Hey beautiful people, can someone help me? I think already enabled mine but still it's not working., Does this count ??

![image](https://user-images.githubusercontent.com/12043306/67160812-25186100-f387-11e9-942c-8fb2b912cca5.png)

This is the link :  https://pastebin.com/UJPYvve8
