### ISSUE TITLE
Error on Build Projet

### ISSUE THREAD

**Issue by ofostier** [hpneo/gmaps#527]
Hi,

When I follow step by step all action to build the project I've got an error

Running "jshint:all" (jshint) task
1 file lint free.

Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom

Running PhantomJS...ERROR
0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

npm : 3.10.9
grunt-cli v0.1.13
grunt v0.4.5
phantomjs: 2.1.1

Any idea ?

**Comment by hpneo** [comment]
I checked and seems to be an issue with the Node version and the `grunt-contrib-jasmine` package. I fixed bug after bug related to mismatched versions and it seems to work fine now (0.4.25).
