### ISSUE TITLE
arrayToLatLng mutates the given object

### ISSUE THREAD

**Issue by NLincoln** [hpneo/gmaps#538]
https://github.com/hpneo/gmaps/blob/master/gmaps.js#L104

I'm using https://github.com/matt-jensen/ember-cli-g-maps, and this function here is causing properties on my objects to be mutated, which is causing a lot of issues.

Possibly want to just create a new array instead?

**Comment by hpneo** [comment]
Fixed in v1.0.0 (alpha)
