### ISSUE TITLE
[How To] Install and display map on Rails 5

### ISSUE THREAD

**Issue by kirantpatil** [hpneo/gmaps#542]
Hi,

I would like to know the steps to install it on Rails 5 and  display map as per quick start guide.

Thanks in advance.

**Comment by kirantpatil** [comment]
Finding it difficult where to declare API key in rails ?

**Comment by darol100** [comment]
@kirantpatil , This is not a Rail app, so there should not be any documentation on how to use this library with Rail 5.

**Comment by darol100** [comment]
You can add the Google API key in the js file. Like this 

https://github.com/hpneo/gmaps/issues?page=2&q=is%3Aissue+is%3Aopen#issuecomment-279352401
