### ISSUE TITLE
Specifying google maps Key

### ISSUE THREAD

**Issue by KillWil** [hpneo/gmaps#543]
Hello,

When including this in my development :

`<script src="https://maps.google.com/maps/api/js"></script>`

it works like a charm but have a warning about using google maps without key.

When adding key like this : 

`<script src="https://maps.google.com/maps/api/js?key=MYKEY"></script>`

The key is created in the google developper console Added domain and subdomains to the API console (*.domain.com/\* , domain.com/\*)

It does not work :

`Uncaught TypeError: Cannot read property 'prototype' of undefined
    at common.js:47
    at Object._.Ua (js?key=MYKEY:33)
    at a (common.js:47)
    at Om (common.js:47)
    at common.js:50
    at Jm.en (common.js:189)
    at Object.c [as _wqkr3e] (common.js:45)
    at AuthenticationService.Authenticate?1shttp%3A%2F%2Fwww.mydomain.com%2Fsubdirectory%…:1`

Can you help?
Thanks a lot!

**Comment by miladghiravani** [comment]
Hi

try this:
```
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&key=YOUR_API_KEY"></script>
<script src="gmaps.js"></script>
```
You need to get api key from google. It's free and no need to register for site address (you can get and use this on localhost and ...)
**Get google map api:** https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by dleffler** [comment]
I think 'sensor=true' is deprecated so
```
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=YOUR_API_KEY"></script>
<script src="gmaps.js"></script>

**Comment by hpneo** [comment]
@sbgraphic You can use [Mapbox](https://www.mapbox.com) or [Leaflet](https://leafletjs.com/)
