### ISSUE TITLE
Capturing marker click event 

### ISSUE THREAD

**Issue by ikeashark** [hpneo/gmaps#545]
I would like to capture a marker click to then be able to display the clicked marker details in a div beside the map. How would i be able to take the marker extract the information i need. Any sample codes or advice to point me in the right direction would be greatly appreciated. 

Coding in javascript and jquery in google chrome browser.

My code currently to add event to marker:
``` 
$(document).ready(function() {

map.addMarker({
                        lat: lat,
                        lng: lng,
                        title: 'Marker #' + index,
                        infoWindow: {
                            content: content
                        },
                        details: 'default marker details',
                        click: function(e) {
                            alert(e.lat);
                        }
                    });
});
```

however when i try to get data from the clicked marker with `click: function(e) {alert(e.lat); }` it gives me undefined in the alert box.

Thank you

**Comment by stivoox** [comment]
any update or solution ?

**Comment by ikeashark** [comment]
Its a mistake with calling of the lat and lng

Wrong:
`e.lat;`

Correct:
`e.latLng.lng();`

I have not worked on this project for a while now so it might not work, `sorry.`
