### ISSUE TITLE
Remove specific polyline

### ISSUE THREAD

**Issue by davidshieldsaz** [hpneo/gmaps#549]
I'm creating the polylines using drawRoute and gmaps.  I've looked through all the issues in your git but I can't find an example to help with my issue.  You mentioned here https://github.com/hpneo/gmaps/issues/379 that I need to pass the polyline as the object, but i'm having trouble doing that after the polyline has been created.  I have setinterval code running that uses ajax to update the map.  I want to remove a specific polyline from the map if it matches an ID that's coming from the ajax call.  I'm able to remove the last polyline using map.polylines[map.polylines.length - 1] and the callback, but if I create more than 1 polyline, I need to be able to remove it based on an ID.  Can you please help me with this, I can pay you?

To reiterate the way i'm using the gmaps code. I'm using a foreach loop to iterate through routes on my map.  I'm using drawRoute to create the polyline.  Every 10 seconds an ajax call is made through setinterval to my database, if the database has been updated so that one of the routes needs to be removed, then I want to remove the polyline from the map. Just to be clear, i'm using polylines and routes interchangeably in my description of this issue.  I've tried creating a global variable that's defined by the route ID coming from the database so that I can try and remove the route based on the route ID, but it doesn't work.  I'm sure this is a very easy issue that would be simple for you to help me with, just can't get my mind around it.  I would greatly appreciate your help.

**Comment by hpneo** [comment]
Sorry I couldn't help you with this. I'll close this issue, but if you need any further help let me know.
