### ISSUE TITLE
Poor Documentation

### ISSUE THREAD

**Issue by stivoox** [hpneo/gmaps#563]
i don't have a  technical issue , but this plugin need more detailed documentation  : for example we don't know what means : 
div — HTMLDivElement 
controls — Array 
overlays — Array 
 etc...

For example i'm looking for maps options but i can't see any documentation about that . 

most rated google maps plugin need better doc .

regards .

**Comment by hpneo** [comment]
You're right @steenhulthin, and really sorry for the late reply. I'll work on that (see #585)
