### ISSUE TITLE
Region Maps?

### ISSUE THREAD

**Issue by jglazer63** [hpneo/gmaps#571]
In the google API it has the ability to display a map of a region.  Say "Cleveland" or "Ohio".  I am really interested in being able to display a complete U.S. State inside a defined div.  I cannot seem to find a way to do this with gmaps.js.    Any help?

**Comment by abrhambas01** [comment]
You mean autocomplete ? 

[](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
)
(https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
)
Heres the link

**Comment by hpneo** [comment]
@jglazer63 sorry for the late reply. I think you can use https://developers.google.com/chart/interactive/docs/gallery/geochart
