### ISSUE TITLE
Show user's location?

### ISSUE THREAD

**Issue by Dubz** [hpneo/gmaps#577]
Is there a way I can add the user's current position using the blue dot, similar to what Google Maps does when you go to it? I'd like people to see where they're at, but not blend them in using the same markers as other places.

**Comment by memo-rebolledo** [comment]
You can try getting the latitude and longitude of the user using the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API). Then [create a marker](http://hpneo.github.io/gmaps/documentation.html#GMaps-createMarker) with [options to customize it](https://developers.google.com/maps/documentation/javascript/reference/3/#MarkerOptions).

**Comment by hpneo** [comment]
Thanks @ghost!
