### ISSUE TITLE
Is Gmaps broken right now?

### ISSUE THREAD

**Issue by snazaca02** [hpneo/gmaps#583]
I've been using Gmaps with great results for a couple years now. 

Noticed that last wednesday now all my maps are throwing script errors without any changes to my code or  my api key. 

Tried going to your website http://hpneo.github.com/gmaps/ 

Its saying that google maps can't load on that page.

**Comment by stykoss** [comment]
Me too

**Comment by moosa22** [comment]
thats right

**Comment by gunner1095** [comment]
Google maps API now requires an API key. 

https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
