### ISSUE TITLE
I want to display multiple windows.

### ISSUE THREAD

**Issue by ztsuzuki** [hpneo/gmaps#591]
Thanks to gmaps.js I was able to carry out my work. Thanks for the great plugin.

Let me ask you a question.
I think it is probably a map with multiple markers by default, and the window that appears when you click on the first marker disappears when you click on another marker.
Is it possible to open another window without deleting the current window?

By the way, the version of gmaps.js loads the following
https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js

I'm sorry if you had the same question in past issues.
Please reply to me.

**Comment by hpneo** [comment]
Hi @chanNORI, currently there's no option to do that, but you can patch GMaps to allow that behavior.

When you click on a marker, if the marker has an info window, it'll call [`self.hideInfoWindows()`](https://github.com/hpneo/gmaps/blob/master/lib/gmaps.markers.js#L77), which [will close all the opened markers](https://github.com/hpneo/gmaps/blob/master/lib/gmaps.markers.js#L141).

You can override `hideInfoWindows` to don't do anything.

**Comment by ztsuzuki** [comment]
Thanks for the quick reply!

I took your advice and overruled it with the following code, and I was able to keep multiple windows open!
`
      GMaps.prototype.hideInfoWindows = function() {
       # for (var i = 0, marker; marker = this.markers[i]; i++){
          if (marker.infoWindow) {
            // marker.infoWindow.close();
          }
        }
      };
`

Thank you so much!

**Comment by hpneo** [comment]
No prob!
