### ISSUE TITLE
"This page can't load Google Maps correctly." -- Error

### ISSUE THREAD

**Issue by dhanediesil** [hpneo/gmaps#592]
Hey there,

I added the code to my site but got the error mentioned below:
<img width="1440" alt="Screen Shot 2020-11-28 at 2 30 14 PM" src="https://user-images.githubusercontent.com/75186017/100527361-b2cba000-3186-11eb-8cfe-35567072ae8a.png">

Not sure why that's happening.

Please advise on a fix.

**Comment by hpneo** [comment]
Hi @dhanediesil, did you follow the steps mentioned here https://github.com/hpneo/gmaps/issues/580 ?

**Comment by dhanediesil** [comment]
I didn't notice that when I was skimming the other issues. Thanks for
letting me know.

**Comment by mroswell** [comment]
I get the "This page can't load Google Maps correctly" error upon visiting every map on: 
https://hpneo.dev/gmaps/
I just discovered the project, felt excited to find it... I would have more confidence in the project if the samples all worked without that error.

**Comment by hpneo** [comment]
Hi @mroswell. This error is due to the website not having a Google Maps API key. Since Google charges for using the Maps JavaScript API and this project is free, not using an API key is my only option right now.
