### ISSUE TITLE
Not able to remove Routes

### ISSUE THREAD

**Issue by vultureonline** [hpneo/gmaps#73]
If I use the function map.getRoutes(), the callback returns the current added routes of the map object.
If I issue multiple calls to the .getRoutes() function, the routes add up to the routes[ ] array of the map object.

Is there a way to clear the map.routes[ ] array?
I thought the function removePolylines() should do this, but it doesn't.

Is it possible to add this functionality?

**Comment by redhot2323** [comment]
any update on how to remove the drawn routes? like if I draw a route and then redraw another one. I only want 1 route display.
I can't find how to remove drawn Routes.

**Comment by knapeto** [comment]
Hi any solutions for remove the drawn routes ? Thanks

**Comment by hpneo** [comment]
Not really. I didn't implement `removeRoute`, but you can do something like:

```javascript
var drawnRoute;

map.drawRoute({
  ...,
  callback: function() {
    drawnRoute = map.polylines[map.polylines.length - 1];
  }
});
```

And remove it with:

```javascript
map.removePolyline(drawnRoute);
```
